### ISSUE TITLE
WP Table prefix hash

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#101]
Maybe we could generate a short hash instead using project name slug?

**Comment by jakub300** [comment]
Why would it be better than slug itself? Because of potential slug length?

**Comment by luboskmetko** [comment]
As a small security enhancement although [some people say it's pointless](http://wpkrauts.com/2015/the-database-prefix-is-not-a-security-feature/). But see the discussion too, if we can have it setup automatically, why not.
