### ISSUE TITLE
Document wildcard Apache virtual host and wildcard DNS

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#102]
To avoid setting up a vhost on each project, adding new entry to hosts file and restarting server, we could document a better way (either here or as a blog post)

Some resources:

- http://brunodbo.be/blog/2013/04/26/setting-up-wildcard-apache-virtual-host-wildcard-dns
- http://stackoverflow.com/questions/138162/wildcards-in-a-windows-hosts-file/272092#/

An example of my Windows XAMPP installation (update directory structure according your setup):

**hosts file**
no entries needed

**httpd.conf** - uncomment the following module
```
LoadModule vhost_alias_module modules/mod_vhost_alias.so
```

**httpd-vhosts.conf**
```
<Directory "C:/xampp/xampp/htdocs/www/">
     Options Indexes FollowSymLinks Includes ExecCGI
     AllowOverride All
     Order allow,deny
     Allow from all 
 </Directory>

# so localhost still works
<VirtualHost *:80>
    ServerName localhost
    ServerAlias localhost
    DocumentRoot c:/xampp/htdocs/www/
</VirtualHost>

# wildcard vhost
<VirtualHost *:80>
    ServerAlias *.dev
    VirtualDocumentRoot c:/xampp/htdocs/www/%-1/%-2+/wp #notice wp at the end, that's because Chisel serves WP from a subfolder
</VirtualHost>
```

Then running [Acrylic DNS Proxy](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome) with the following in **AcrylicHosts.txt**

```
127.0.0.1 localhost localhost.localdomain
::1 localhost localhost.localdomain
127.0.0.1 *.dev
```

Plus [Windows 10 configuration](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration) to set Acrylic DNS

Now when you create a Chisel WP project in `dev` folder eg. `c:/xampp/htdocs/www/dev/awesome-site` the site is immediately accessible at `awesome-site.dev`

You can create different wildcard hosts for different types of projects like here http://serverfault.com/a/503299

**Comment by thymikee** [comment]
@luboskmetko  This is much needed especially for front-end developers not familiar with Apache and WP. I'd like to make this a priority.

**Comment by thymikee** [comment]
I've just documented a detailed installation workflow for macOS users and link to proper articles and your config here: https://github.com/xfiveco/generator-chisel/wiki/WordPress-workflow

@luboskmetko Please update this wiki page with your config on Windows, as I'm just linking it now

**Comment by luboskmetko** [comment]
Thanks, done
