### ISSUE TITLE
Adding pages to WordPress projects

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#103]
It would be nice to have a possibility to run `yo chisel:page` subgenerator in the WP project. 
@JakubSzajna can you please advise on this issue?

**Comment by luboskmetko** [comment]
This is also task for @jakub300 - when `yo chisel:page` is run on WP project it should create `page-name.twig` from template, so it's a similar functionality we already have for front-end projects.

The other step which is needed is adding a new page in WP admin. I guess we'd need to use https://wp-cli.org/commands/post/create/ if we want to do it from command line. 

Until we have this ready, I'll update docs with info about these 2 steps.

**Comment by jakub300** [comment]
Fixed in 7e712f9d15e7dbcc3756c81fdd282adfdf97eb01
