### ISSUE TITLE
Easier front-end development in WP projects

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#105]
Based on Kate's feedback, I imagine that at some point we could make front-end development setup at WP projects automated to that extend that front-end developer doesn't need to touch WP admin at all. There is a node wrapper for WordPress CLI, even though it looks it's not been updated for a while https://github.com/gtg092x/node-wp-cli

This would allow to split project development to 2 phases - front-end and WP and allow client to approve templates before WP development starts. At the same time we would still have all advantages of developing front-end and WP in the same code base.

Here are steps, I guess it would require:

1. Basic scaffolding of WP project type - done
2. Wildcard vhosts - documented
3. Automated database creation - #100 
4. Core WP install - https://wp-cli.org/commands/core/install/
5. Activate Timber plugin - https://wp-cli.org/commands/plugin/activate/
6. Activate Chisel starter theme - https://wp-cli.org/commands/theme/activate/
7. Adding pages to WP projects - #103 (using WP cli to create pages in WP)
8. Basic navigation through existing pages - it's already in the starter theme (newly added pages are listed there), but maybe we could make default home page in WP project look same like the project index in the front-end projects.

Let me know what you think.

**Comment by jakub300** [comment]
From my testing: many WP-CLI operations like activation of plugin/theme, creation of a post require access to database so it will not work if env variables are used.

**Comment by luboskmetko** [comment]
Good to know, but I think benefits of using wp-cli to automate various operations are worth using DB credentials in local config instead env variables. I've just tried it too, installation on Windows was a bit cumbersome for me, but now it works nice.

**Comment by jakub300** [comment]
so, do we now require plain text credentials during generation or should I prepare separated handling (no wp-cli, etc.) for situation when user gives env variables?

**Comment by luboskmetko** [comment]
Don't know what that separate handling means exactly but I would use WP-CLI for everything and only skip steps which require proper DB credentials (you will need to take care of that anyway, if user provides wrong credentials).

I don't use env variables so if that's up to me we could leave them out completely but maybe talk to other WP developers first. env variables make manual installation easier because you can avoid one wp-config.php edit but if we make the whole WP install automatic, using them doesn't make that much sense anymore.

If it comes to easier project setup, in the XH generator we had an option to [scaffold the project from provided `yo-rc.json` ](https://github.com/xfiveco/generator-xh#1-project-scaffolding). This would be handy at some point, and I imagine that part of it could be a file with local DB credentials (of course, it cannot be committed).

**Comment by jakub300** [comment]
@luboskmetko Should that be closed now?

**Comment by luboskmetko** [comment]
@jakub300 let's leave it open yet as I'm still working on #112 which should complete this. Of course, we could release new version with what we have in the meanwhile.

**Comment by luboskmetko** [comment]
Actually, closing this as a basic navigation through existing pages already exists and further starter theme improvements would be done a bit differently (not using front-end index, but rather white label theme)
