### ISSUE TITLE
Role of composer in WordPress projects

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#111]
Currently we are installing both WordPress and  plugins via composer. Due to a bug (not removing `.git` directories from plugins, not topic of this issue) plugins do not work properly, but beside that there are several problems that should be discussed.

### Should plugins be stored in the repository?
Until yesterday I thought that our goal for using `composer` for plugin installation is that developer would install and update plugins via composer locally and then commit them into repository. In that case it would not be required to run composer on the server. @JakubSzajna and @thymikee on the other hand thought that we are (should) ignoring plugins (add them to .gitignore) and do not store them inside the repository.

### Role of composer in installation and updates of WordPress
One quick fact: currently updating WP by `composer update` is removing WP directory and recreates it with new WP version which means that config, installed plugins, theme, uploaded files [are gone](https://www.youtube.com/watch?v=DNLob2E_Q5s).

Author of WordPress composer package [recommends](https://github.com/johnpbloch/wordpress/issues/8) storing `wp-content` directory outside of wordpress itself. Alternative is to remove WP from composer after installation like we did with starter theme in the past and updating it with its built-in updater.

**Comment by jakub300** [comment]
Random thought: since we are considering use of WP-CLI for various things we may also use it to [download WordPress](https://wp-cli.org/commands/core/download/).

**Comment by luboskmetko** [comment]
Normally, I would agree we should git ignore what's installed as a dependency via composer (plugins, even WP) but wondering if it wouldn't be safer if those are committed too. For example if someone wants to use BackupBuddy to backup whole site from the server. Or other developers most likely won't have Composer installed on server where they deploy their sites.

As for WP installation, I would rather avoid moving `wp-content` folder to avoid increasing complexity and potential issues. WP-CLI might be a good solution as we'd like to use it anyway. Then wondering if we shouldn't use it for installing plugins too if Composer doesn't work properly. We would need a configuration file to store list of plugins, not sure how it would be with those premium plugins.

**Comment by JakubSzajna** [comment]
@luboskmetko how is composer installed plugins related to the problems of using BackupBuddy? If you install plugins with composer they are simply downloaded from the repository and placed inside plugins directory.
I see another problem - if we ignore plugins installed via chisel we would still have problems with other plugins installed directly via composer.
The solution is to ignore whole plugins directory and exclude only those loaded manually. But with this approach everyone would have to remember to exclude plugins directory from .gitignore when manually adding plugins.

**Comment by luboskmetko** [comment]
@JakubSzajna you're right, backup shouldn't be a problem as plugins are there anyway. What you described as that other problem could cause a lot of confusion.

Now I'm wondering if there is any benefit in having plugins installed via Composer. One is having often used plugins installed during project scaffolding but this could be achieved via WP-CLI too (and plugins can be even activated). But when you join the project as new developer or when transferring site you still need the whole DB dump to preserve all settings and content. Composer won't help you to solve this problem and only adds new level of complexity. What you think?

**Comment by JakubSzajna** [comment]
Yes, I've checked the WP CLI and it seems a lot better solution than composer. It doesn't need any repos, loads plugins from wordpress.org, has ability to even search the plugins database.
And we want to use it either way, so I also think we should get rid of composer and stick with hte WP CLI.

About the problem with joining project - I don't think there is a solution for that. We can create a public database engine that everyone can use, this will also improve the team work performance, as you don't need to copy someone's changes to your local database. But this is not related to chisel, and is not a safe solution to that.

**Comment by luboskmetko** [comment]
Right, joining project is a different issue, I just wanted to point out that Composer would make much more sense if joining the project would just mean cloning the repo and running `composer install` but on WP project it requires importing a DB dump in which plugins are defined too.

**Comment by luboskmetko** [comment]
Closing this one as we've already replaced Composer with WP CLI and it should be released soon.
