### ISSUE TITLE
Twig function for images urls - imagePath

### ISSUE THREAD

**Issue by marziolek** [xfiveco/generator-chisel#118]
assetPath should work not only for css/js but also for images.

Edit: No revision needed.

**Comment by jakub300** [comment]
I'm not a fan of that The only purpose of `assetPath` is to set names for revisioned files. I would rather rename `assetPath` to `revisionedPath` and throw exception if trying to use on path that doesn't exist in `rev-manifest.json`

**Comment by jakub300** [comment]
Could somebody describe please what this function should be doing?

**Comment by luboskmetko** [comment]
As I understand it if you write `{{ asset('images/logo.svg') }}`, it should generate a link `assets/images/logo.svg` or whatever the assets folder is

**Comment by jakub300** [comment]
Ok, I can do that but it's literally less characters to write full path instead of using function.

**Comment by luboskmetko** [comment]
That's right, maybe @marziolek could confirm if this is what he was up to?

I can imagine that the function could be useful if you try to change location of assets, although, it probably would be a rare situation.

**Comment by jakub300** [comment]
@thymikee

**Comment by thymikee** [comment]
https://github.com/xfiveco/generator-chisel/issues/119#issuecomment-263873747
cc: @marziolek @luboskmetko

**Comment by marziolek** [comment]
@luboskmetko I believe that [https://github.com/xfiveco/generator-chisel/issues/119#issuecomment-263873747](#119) is best approach here. Thanks!

**Comment by mortensassi** [comment]
I'm trying to use `assetPath` with `{{ source(myPath) }}` but unfortunately i get an error:

```
Fatal error: Uncaught Twig_Error_Loader: Unable to find template "http:/MYSITE.lo/wp-content/themes/MYSITE/dist/assets/images/logo.min.svg" (looked into: /app/public/wp-content/themes/MYSITE, /app/public/wp-content/themes/MYSITE/templates, ). in /app/public/wp-content/themes/MYSITE/templates/components/header.twig on line 5

Twig_Error_Loader: Unable to find template "http:/MYSITE.lo/wp-content/themes/MYSITE/dist/assets/images/logo.min.svg" (looked into: /app/public/wp-content/themes/MYSITE, /app/public/wp-content/themes/MYSITE/templates, ). in /app/public/wp-content/themes/MYSITE/templates/components/header.twig on line 5

```

when i copy the url-path i can open the svg. Any help would be great!

**Comment by marcinkrzeminski** [comment]
Hi @mortensassi,

Did you try to use `{{ assetPath(path) }}`?

**Comment by mortensassi** [comment]
@marcinkrzeminski Yeah and it works, but i want to extract the SVG code so i can embed it inline when i need it.

`dump(assetPath('images/logo.min.svg'))` outputs this:

`/app/public/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Extension/Debug.php:60:string '//localhost:3000/wp-content/themes/MYSITE/dist/assets/images/logo.min.svg' (length=71)`

**Comment by marcinkrzeminski** [comment]
@mortensassi I see. 

In that case you have two options.

1. Use a global definition for you SVGs. I usually create a component like icons.twig and include it after `<body>`. Here's an example:

```
<svg style="position: absolute; width: 0; height: 0;" width="0" height="0" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <symbol id="svg-logo" viewBox="0 0 24.161 19.597" xmlns="http://www.w3.org/2000/svg">
      <title>Logo</title>
      ... 
    </symbol>
  </defs>
</svg>
```

Once that done you can reuse is like this:

```
<svg class="c-logo__image">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-logo"></use>
</svg>
```

2. Create a component like `logo.twig` and use it like this `{% include 'components/logo.twig' %}` wherever you want. Keep in mind you can pass variables to your include as well like `{% include 'components/logo.twig' with { css_class: 'c-logo__image' } %}` .

Hope that helps ;).

Personally, I prefer the first option.

**Comment by mortensassi** [comment]
@marcinkrzeminski thank you! I also used the first approach but i have noticed an increase in the filesize of every document (Start, about, etc.) because of a lot of icons that end up not used in some pages so i thought about storing SVGs each in the `assets/images` folder and working with the `{{ source  }}` function to inject only the XML-Code i need. 

A plugin which acts like the media uploader would be great in the end so you could offer your users the ability to "upload" svgs which automatically get injected as needed. 

What do you think?

**Comment by marcinkrzeminski** [comment]
@mortensassi It all depends on the use case. If you have a few icons I'd say it's not a big deal. Even with bigger number + gzip + caching not a big deal as well in my opinion. It's the same as using sprite images back in the days :). 

However, now I fully get it what you have in mind. I've tried these and it worked for me:

```
{{ source(heme.path() ~ '/dist/assets/images/logosvg') }}
{{ source('dist/assets/images/logo.svg') }}
```

Hope that helps ;).
