### ISSUE TITLE
Rename assetPath

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#119]
Currently assetPath has nothing to do with assets. The only purpose of `assetPath` is to set names for revisioned files. I would like to rename `assetPath` to `revisionedPath` and throw exception if trying to use on path that doesn't exist in `rev-manifest.json`

**Comment by jakub300** [comment]
@thymikee

**Comment by thymikee** [comment]
We had a little brainstorming in the office and came out with the idea of extending functionality instead of renaming it:

* `assetPath()` – points to `dist/assets/`, this is a plain helper function
* `revisionedPath()` – points to `dist/` and requires underlying styles or scripts to be revisioned.
