### ISSUE TITLE
Make page lists merge-friendly

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#122]
Currently when creating two different pages on different branches later rebasing one on the top of another or merging them one on top of another is creating conflicts in `.yo-rc.json` and `index.html`. I don't know how but it would be nice to make it possible to rebase/merge without conflicts.

**Comment by luboskmetko** [comment]
@jakub300 is this doable in some reasonable way/time? Are you planning to work on it?

**Comment by jakub300** [comment]
I don't see simple solution for that, I'll close it for now.
