### ISSUE TITLE
Scripts error swallowing in watch mode

### ISSUE THREAD

**Issue by danekszy** [xfiveco/generator-chisel#125]
Syntax errors aren't displayed in gulp in watch mode.
This happened in my project with Babel turned on, so I still need to do some research and test out the clean copy of the generator.

I'd also be happy to dig into this whenever I have some free time (today/tomorrow).

**Comment by jakub300** [comment]
I failed to reproduce without Babel:
![image](https://cloud.githubusercontent.com/assets/610941/20712818/09e99204-b646-11e6-9ed7-b9519b7e901b.png)
And with babel:
![image](https://cloud.githubusercontent.com/assets/610941/20712849/2b29754c-b646-11e6-8ee6-58fb27948058.png)

**Comment by danekszy** [comment]
Cool. Thanks @jakub300, this will help me with debugging :)

**Comment by danekszy** [comment]
Couldn't reproduce it either. Turns out it was a problem in older version of generator (deployed in my project some time ago).
Again, thanks @jakub300 👍
