### ISSUE TITLE
Get rid of _prefixed templates, compile root level .twigs

### ISSUE THREAD

**Issue by danekszy** [xfiveco/generator-chisel#131]
As per @luboskmetko idea in #130 we're considering getting rid of `_` prefixes for private templates in favor of compiling only root level templates as separate pages.
This would limit template usage (we couldn't use it as a static site generator as easily), but I'm guessing this isn't that big of a use case for our developers.

This new approach would also simplify the stucture for wordpress type projects, which may use some complicated folder structures for different types of template elements/dependencies.
Let me know if any one of you have any concerns... Otherwise I will try and implement this new approach and clean up the code a bit.
Thanks guys!

**Comment by jakub300** [comment]
That is already the case or it should be -> #108

**Comment by danekszy** [comment]
Right, but we still exclude `_prefixed` templates and this is sth we're considering getting rid of.
In turn we could simplify our config, by automatically prefixing globs with our base path...

**Comment by jakub300** [comment]
I don't see the reason to keep prefixes, they are already removed from built-in files.

**Comment by luboskmetko** [comment]
One change this would require is moving `_template.twig` to a subfolder, maybe to `layouts/page.twig` to avoid having `templates/templates` directory.

**Comment by luboskmetko** [comment]
Of course, we also need to update page subgenerator then which uses `_template.twig` to create new pages.
