### ISSUE TITLE
Migrate to Yeoman 1.0

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#138]
There's a new version of Yeoman: http://yeoman.io/blog/hello-generator-1.0.html
We could also move to installing deps with Yarn since this release.

**Comment by luboskmetko** [comment]
I've migrated generator to Yeoman 1.0 to get away "outdated dependencies" notice but didn't do anything with Yarn. Closing this for now, Jakub or you could do more refactoring when you have time.
