### ISSUE TITLE
Create a repository with useful CSS

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#145]
We often create CSS/SCSS mixins, components, objects etc which we like to reuse in other projects. I think it would be a good idea to create a separate repository just for that, so we can share with others and copy & paste when needed.

**Comment by luboskmetko** [comment]
I'm not a big fan of a separate repository. There were such attempts in the past but it always ended unmaintained and not used. If there are some proved reusable solutions (eg. objects or sample components) there should be part of Chisel and we should provide a mechanism of selecting them and copying them to the project.

**Comment by thymikee** [comment]
So we can create a directory inside Chisel repo. It doesn't need to be fancy, just a set of ready-to-copy components and mixins on demand.

**Comment by luboskmetko** [comment]
Sounds good. Later we can see how we allow copying this to the project using chisel commands

**Comment by luboskmetko** [comment]
@thymikee trying to clean up the issues a bit and closing this one. Let's create a separate repository for this as you initially suggested if there is still such need.
