### ISSUE TITLE
Project folder with number in name doesn't match the project slug

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#155]
For example if I run Chisel in a project folder with name `abc1`, the project name/slug in configuration is generated as `abc-1` so the dev domain `abc1.dev` won't work.

**Comment by jakub300** [comment]
Why is that a problem?

**Comment by luboskmetko** [comment]
Because it doesn't work out of box with https://github.com/xfiveco/generator-chisel/wiki/Wildcard-virtual-hosts-and-DNS

If I setup project in `dev/abc1`, it's automatically available at `abc1.dev`. But Chisel proxies it to a nonexistent `abc-1.dev` because it added dash to the project slug.
