### ISSUE TITLE
Document and automate setup of existing WP project

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#156]
When setting up an existing WP project, the following steps are required

1. Clone the repository
2. Run `yo chisel:wp-config`, it should create `wp-config-local.php` and generate `dev-vhost.conf` (if you need it)
3. Create database
4. Import DB dump
5. Run `npm install` and `gulp build`

More automated setup could also:

- allow user to enter name of DB import, if possible offering to select from the names of available SQL files in the project folder
- do DB import using http://wp-cli.org/commands/db/import/
- run `npm install` and `gulp build` automatically

**Comment by jakub300** [comment]
It's definitely great idea to have more automation for joining projects.

One thing that we should keep in mind is that when we are working on WP projects, we are not using DB dumps or anything like that so actual flow for joining projects is even longer:

1. Clone the repository
2. Create database
3. Run yo chisel:wp-config, it should create wp-config-local.php and generate dev-vhost.conf (if you need it)
4. Run npm install and gulp build
5. Setup WordPress with some info
6. Enable Migrate DB
7. Use Migrate DB to import database and files

More automated version would probably use [wp migratedb pull](https://deliciousbrains.com/wp-migrate-db-pro/doc/cli-push-pull-subcommand/).

**Comment by luboskmetko** [comment]
Good point about Migrate DB, I haven't had time to look on that but I'll try to test it and document exact steps for the projects at Getfives.

I was using DB dump in one recruitment project so we can have that documented as an alternative.

**Comment by luboskmetko** [comment]
Usage of  WP Sync DB is documented in https://github.com/xfiveco/generator-chisel/wiki/Setting-up-WordPress-projects-at-Getfives, should be enough for now.
