### ISSUE TITLE
Adjust initial wordpress configuration

### ISSUE THREAD

**Issue by JakubSzajna** [xfiveco/generator-chisel#172]
Maybe you should implement as many security hardening pre-configurations as it is possible?
Everyone can enable special features if he needs them, otherwise it is more secure to keep them disabled.
http://www.wpbeginner.com/wordpress-security/#adminusername
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/19
https://codex.wordpress.org/Hardening_WordPress

I'm not sure how many of those tips are already implemented, so I'm linking everything ;)

**Comment by luboskmetko** [comment]
Ok, I'll try to write a list of what we could implement and later we can make issues of out this:

- the admin user shouldn't be named admin - we can suggest default admin name here https://github.com/xfiveco/generator-chisel/blob/master/generators/wp/index.js#L47, it could be derived from git user first name maybe with some random numbers appended to it so it doesn't match WP author

**Comment by luboskmetko** [comment]
Disable File Editing, Append the following two lines to the end of your wp-config file: 

```
define('DISALLOW_FILE_EDIT', true);
```

**Comment by luboskmetko** [comment]
Maybe disallow access to WP-Config.php, put this in that file (at the very top) to deny access to anyone surfing for it: 

```
<files wp-config.php>
order allow,deny
deny from all
</files>
```

**Comment by luboskmetko** [comment]
We already generate unique keys and salts in wp-config.php

**Comment by luboskmetko** [comment]
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/21

In wp-config.php:

```
define('WP_DEBUG', false);

if ( ! WP_DEBUG ) {
	ini_set('display_errors', 0);
}
``

**Comment by luboskmetko** [comment]
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/24

Hide WP version, this could be done in the functionality plugin

```
remove_action('wp_head', 'wp_generator');
```

**Comment by luboskmetko** [comment]
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/26

Secure login, add to .htaccess

<Files wp-login.php>
	AuthType Basic
	AuthGroupFile /dev/null
	AuthName "What are you looking for"
	AuthUserFile /sciezka-do-htpasswd/.htpasswd
	require valid-user
</Files>

Not sure if I understand this one properly, looks like there could be some issues with it

**Comment by luboskmetko** [comment]
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/27

Disable XMLRPC, again good to add to a functionality plugin

add_filter('xmlrpc_enabled', '__return_false');

**Comment by luboskmetko** [comment]
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/28

In folder `wp-admin` add `.htaccess:`

```
AuthType Basic
AuthGroupFile /dev/null
AuthName "What are you looking for"
AuthUserFile /sciezka-do-htpasswd/.htpasswd
require valid-user
```

**Comment by luboskmetko** [comment]
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/29

Block listing authors, add to `.htaccess`

```
RewriteCond %{QUERY_STRING} author=\d
RewriteRule ^ /? [L,R=301]
```

**Comment by luboskmetko** [comment]
http://wpmagus.pl/pliki/prezentacje/wyczaruj-sobie-spokoj/#/31

protect `wp-includes`

```
<FilesMatch "\.(?i:php)$">
	Order allow,deny
	Deny from all
</FilesMatch>
<Files wp-tinymce.php>
	Allow from all
</Files>
<Files ms-files.php>
	Allow from all
</Files>
```

and `wp-content/uploads`, add .htaccess

```
<FilesMatch "\.(?i:php)$">
	Order allow,deny
	Deny from all
</FilesMatch>
```

Note: this can break some plugins

**Comment by luboskmetko** [comment]
I've created separated issues from the above, except those which require to set path to .htpasswd, not sure if we can set this on Chisel level.
