### ISSUE TITLE
ES6 as an option selected by default?

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#183]
@thymikee @jakub300 @arturkot what you think of making ES6 option selected by default when prompting user to encourage its usage?

I would also move it above jQuery and rename `ES2015 with Babel` to `ES6 with Babel`. Correct me if I'm wrong but looks like it's more commonly used nowadays (online course names, articles, etc.)

**Comment by jakub300** [comment]
Fixed in 6bb3c1964a50cd56fee8a54daa61844fb3fa8190 (#188)
