### ISSUE TITLE
Remove support for Node 4

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#191]
Currently our code is weird mix of ES5 and ES6 syntaxes, that is due to support for Node 4. It has official support until 2018-04-01 but I wonder if we could drop support in Chisel sometime this year and fully embrace native ES6 and require Node 6.5 or newer.

@thymikee @luboskmetko

**Comment by thymikee** [comment]
As soon as we migrate all of our infra to latest LTS I'm all for it 👍

**Comment by luboskmetko** [comment]
I'm for it too.
