### ISSUE TITLE
PHPMailer issue during initial setup

### ISSUE THREAD

**Issue by Kwapi** [xfiveco/generator-chisel#192]
Hi, 
I wanted to try out chisel because it look like something I've been trying to create myself. Good job guys!
Anyway, when running a Wordpress install I got two instances of `phpmailerException`. I put 'mzak_chisel.dev' as my URL and that seems to be what caused the error. Is that URL invalid?

UPDATE:
I re-run the install but changed `mzak_chisel.dev` to `mzak-chisel.dev` and it works. The underscore seems to be the problem.

Here's the stacktrace:
`PHP Fatal error:  Uncaught phpmailerException: Invalid address:  (setFrom) wordpress@mzak_chisel.dev in /var/www/mzak_chisel/wp/wp-includes/class-phpmailer.php:1023
Stack trace:
#0 /var/www/mzak_chisel/wp/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@mzak_...', 'WordPress', false)
#1 /var/www/mzak_chisel/wp/wp-admin/includes/upgrade.php(395): wp_mail('m.zak08@gmail.c...', 'New WordPress S...', 'Your new WordPr...')
#2 /var/www/mzak_chisel/wp/wp-admin/includes/upgrade.php(98): wp_new_blog_notification('Michal Zak', 'http://mzak_chi...', 1, 'The password yo...')
...
`

**Comment by jakub300** [comment]
Hey, it looks like `_` is not valid character in the host name, please try domain without it.

**Comment by jakub300** [comment]
Great, I'll leave this open because it's a bug if we create slugs/domains with `_` by default.
