### ISSUE TITLE
Timber classes not found in PHPStorm IDE

### ISSUE THREAD

**Issue by JakubSzajna** [xfiveco/generator-chisel#197]
Timber has changed their core class names, so the class TimberPost that ChiselPost class extends is not recognized anymore.

New classes are aliased for backward compatibility in timber-library/lib/Timber.php in backwards_compatibility method, but my PHPStorm does not follow aliases.

I think we should change Timber classes that we use to follow new naming standard that timber uses, so in example change TimberPost to \Timber\Post in ChiselPost:
`class ChiselPost extends Timber\Post {`

We should also add comma characters by default after array last elements in functions.php, in example in add_to_twig method to avoid git replacing whole line when the comma is added. PHPStorm has automatic code reformat function that I'm using and I've found out that commas are added and thus creates unnecessary changes in commits on those lines.

Method twig_class_name does not follow wp standards that require spaces after ( and before ) etc. It also has docs for unexisting param $modifiers.

**Comment by JakubSzajna** [comment]
Maybe if we have linters for JS and CSS we should implement linters for WP as well?

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

We can use those rulesets and embed phpcs binary in chisel.

PHPMD and PHPCPD could also be useful, but I haven't tested how it will work with WP. But we could scan only wp-content/themes directory.

**Comment by luboskmetko** [comment]
@JakubSzajna thanks for bringing this up. Can you please create PR with those changes in functions.php you've described? Looks like it shouldn't be much work. I could make a new Chisel release then as there were some other small fixes recently.

Regarding PHP linting I think it's a good idea but let's create a separate issue for that as it might require more work.

**Comment by jakub300** [comment]
@JakubSzajna to be clear `twig_class_name` is really `function twig_class_name($name = '', ...$modifiers)` but for compatibility reasons we are using `func_get_args()`. instead of `...$modifiers`. I'm not sure how it should be documented, please let us know if you know.

**Comment by mortensassi** [comment]
Any news on this? Still seeing the get_context method which is [deprecated](https://timber.github.io/docs/reference/timber/#context) and why are you using `Timber\Timber` instead of just a single `Timber`?
