### ISSUE TITLE
As of npm@5, `prepublish` scripts are deprecated

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#199]
@jakub300 this is what I got today:

```
$ npm publish
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> generator-chisel@0.6.4 prepublish .
> php -r "copy('https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar', 'helpers/wp-cli.phar'); if(!file_exists('helpers/wp-cli.phar')) exit(1);"

+ generator-chisel@0.6.4
```

I guess it's not critical but can you take a look when you have time? Thanks

**Comment by jakub300** [comment]
It's important to note that `prepare` event that should be used now has been added in npm 4.0.0 which means that all npms bundled with nodes < 7.4 don't support that event. While this event is not relevant for normal chisel users (only for developers) I would prefer not to limit node versions for developers so significantly right now.

**Comment by luboskmetko** [comment]
Ok, thanks for the info. Closing this for now.
