### ISSUE TITLE
Hide PHP errors

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#212]
In wp-config.php:

```
define('WP_DEBUG', false);

if ( ! WP_DEBUG ) {
	ini_set('display_errors', 0);
}
```

**Comment by JakubSzajna** [comment]
I'd add init_set just above `/** Absolute path to the WordPress directory. */` but I would not add additional WP_DEBUG set to false to allow setting debug to true in wp-config-local
