### ISSUE TITLE
Allow non latin characters in page name when adding WP page on Windows

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#228]
Adding page with non latin characters in name throws an error in WP project

For example:

```
$ yo chisel:page "Hello2 Wąęśźorld 2 :D"
Error: Could not insert post into the database

[path truncated]\generator-chisel\helpers\index.js:21
        throw err;
        ^
1
```

It works in a front-end project.

**Comment by jakub300** [comment]
Hey Lubos,

It is working fine on Mac:
```
Jakub-B-iMac:chisel-test2 jakubbogucki$ yo chisel:page 'Hello2 Wąęśźorld 2 :D'
Success: Created post 3.
   create wp/wp-content/themes/chisel-test2/templates/page-hello2-waeszorld-2-d.twig
All done!
Jakub-B-iMac:chisel-test2 jakubbogucki$
```
I will test it at Windows at some point.

**Comment by marcinkrzeminski** [comment]
Hi,

tested on my MBP and it works as well. @luboskmetko what's your setup? Did you test it with the latest changes including Node 6, etc? 

```
→ yo chisel:page "hello ęąśżźćńłó"
Success: Created post 3.
   create wp/wp-content/themes/chisel-latest/templates/page-hello-easzzcnlo.twig
All done!
```

**Comment by luboskmetko** [comment]
Hey guys,

I still get the same error - Windows 10, Node v9.2.0, Apache/2.4.18, PHP/7.0.1, 10.1.9-MariaDB. I've tried Conemu, Git Bash and Windows PowerShell. I guess this has something to do with encoding, similarly like here https://github.com/wp-cli/wp-cli/issues/1873. I'll try some direct `wp-cli` command when I have more time.  So this is not urgent as it's seem to be a very specific case.

**Comment by luboskmetko** [comment]
Was trying direct `wp-cli` command for creating post and it produces the same error. Tried to change code page for Windows command line but it didn't help. Closing as _wonfix_.
