### ISSUE TITLE
Stylelint is not ignoring vendor

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#229]
It's related to update of gulp-stylelint to v4 and stylelint itself to v8.

@luboskmetko if you have a moment please set gulp-stylelint to 3.9.0, update lockfiles and relase update.

**Comment by luboskmetko** [comment]
I was testing this with stylelint CLI v8 and it seems to respect our `.styleignore`

Could anything here https://github.com/olegskl/gulp-stylelint/compare/3.9.0...master could be causing it? I can revert version back to 3.9.0 but would like to also submit an issue to gulp-stylelint or stylelint

**Comment by luboskmetko** [comment]
Just for a reference - stylelint CLI command for testing in Chisel

```
stylelint "src/styles/**/*.scss" --config .stylelintrc.yml
```

**Comment by luboskmetko** [comment]
Created an issue here https://github.com/olegskl/gulp-stylelint/issues/85

**Comment by jakub300** [comment]
Hey, I've asked for locked release because I had no time to debug. [Stylelint had some changes to ignoring in v8](https://github.com/stylelint/stylelint/pull/2464) so probably something doesn't play nice with gulp-stylelint. If you have a moment it would be nice to create example (without chisel) and add it in the issue you created.

**Comment by luboskmetko** [comment]
@jakub300 I'll make a new Chisel release by tomorrow if there is no feedback from the gulp-stylelint author. In the meanwhile we have a temporary fix listed here.

Btw. what you meant by updating lockfiles. We don't have lockfiles in generated project, do we?
