### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by adamsfather** [xfiveco/generator-chisel#239]
In lot of cases website owners do not optimize images uploaded to their websites. 
Large images are often causing page load time issues which could be avoided.
Adding such workaround (plugin) which would optimize images while they are uploaded would mean lot to performance enhancement with the least of website owner effort.

Comparison of such image optimizer plugins:
http://crunchify.com/wp-smush-it-must-have-wordpress-plugin-for-image-optimization/

**Comment by adamsfather** [comment]
In extension to image optimization there would be nice to have sort of "global WP theme" optimization. Here are some tips: https://www.keycdn.com/blog/google-pagespeed-insights-wordpress/

Some of them could be doable within WordPress, some of them need server configuration.

**Comment by jakub300** [comment]
Hey Stano @adamsfather,

The problem with image optimizations is that all(?) image optimizations plugins are sending images to third party services that do the magic. They also have various limitations like number of images or file size and offer pro versions that lift them. Because of those things I think we should not install any by default. We could engage with the clients about that but this is not related to Chisel itself.

Regarding general theme optimisation I think we are quite good, #234 is only thing that bothers me personally. Also plugins like Gravity Forms makes things uglier from performance perspective. As soon as one of the pages I was working on recently is deployed to production I will share pagespeed link with you.

**Comment by luboskmetko** [comment]
I think we could test a few of these plugins, for example looks like Smush doesn't have very strict limitations. Adding such plugin to the list of available plugins during the project setup, shouldn't do any harm. 

When it comes to performance, we still have a few things to implement in Chisel like:
- web fonts loading
- critical CSS
- cache control for statics assets like CSS/JS/images - this is often not properly setup and if we can set it up with .htaccess we could try (if it doesn't cause any issues)
- Gzip compression with .htaccess - less likely to be missing on live sites, but still happens
- maybe some WP cache plugin

**Comment by adamsfather** [comment]
Found this:

EWWW Image Optimizer
One of the advantages of EWWW Image Optimizer is that the optimization process takes place within your own servers by default, instead of connecting to a third party service.

**Comment by jakub300** [comment]
Generally to improve image performance I would add a recommendation to developers that they should never use original uploaded image, instead they should always use image scaled by WordPress or Timber. While not as good as remote optimizer that itself can significantly reduce image sizes.

@luboskmetko 
`Smush all standard web-sized images 1MB or smaller.` - that's quite a limitation. Sure, adding to the list is not a problem, but using them (even on x5view) without client permission is not something I would like.

Regarding things to implement I really think there is not much we can do without engaging the clients, updating .htaccess is fine but caching plugins conflict with platform level caching ([WP Engine](https://wpengine.com/support/disallowed-plugins/), [Pantheon](https://pantheon.io/docs/unsupported-modules-plugins/#caching-plugins-eg-batcache-w3-total-cache-or-wp-super-cache)) so it's something I would also not add by default.

@adamsfather 
Oh, I missed it but [it requires binaries for optimizers](https://wordpress.org/plugins/ewww-image-optimizer/#installation) which will probably not work on most non-dedicated hostings (including WP Engine and Pantheon). [WP Engine even explicitly bans it](https://wpengine.com/support/disallowed-plugins/).
```Ensure jpegtran, optipng, pngout and gifsicle are installed on your Linux server (basic installation instructions are below if they are not). You will receive a warning when you activate the plugin if they are not present. This message will go away once you have them installed.```
Again I things this is not something we should throw at client as a surprise.

**Comment by adamsfather** [comment]
There's no statement "by default" @jakub300 - adding things to Chisel as Lubos mentioned could be optional.

Who's authority who checks website performance on our client's projects?

**Comment by luboskmetko** [comment]
I agree the preferred way should be using images which are scaled by WordPress or Timber, we can mention this in the dev guidelines. We can even adjust default JPG compress level in WP from 90% to 80%.

Yep, ideal situation is when caching is done by hosting like Pantheon, so maybe we could just recommend some plugin in guidelines for situations when hosting doesn't have caching.

**Comment by marcinkrzeminski** [comment]
Hi,

I did some testing lately comparing a free version of Smush and Imagify and Imagify does a much better job than Smush - at least in my situation. 

Can you tell me what's the actual task here? Writing some guidelines or something else?

**Comment by luboskmetko** [comment]
Closing this one as there isn't much we can do on Chisel level unless there is some free image optimization plugin everyone would agree on. Let's try to address this in a blog post or some guidelines.
