### ISSUE TITLE
Unminified version of styles

### ISSUE THREAD

**Issue by JakubSzajna** [xfiveco/generator-chisel#240]
Maybe we should add possibility to build both, minified and unminified version of css file? When client wants to edit css by himself on already built project there is no unminified version of css file to edit.

**Comment by luboskmetko** [comment]
This is related to #175 but I have some doubts if this should be a part of Chisel. It's promoting bad development and performance practices. If a client wants to use this on their own risk, we can set it up for them manually.

**Comment by luboskmetko** [comment]
Unminified version of CSS should be generated when commenting out this line https://github.com/xfiveco/generator-chisel/blob/master/generators/app/templates/gulp/tasks/styles.js#L30. I suggest that we just document how to achieve this instead making changes to Chisel.

**Comment by jakub300** [comment]
Alex also suggested that we could provide both minified and unminified bundles in dist.

**Comment by luboskmetko** [comment]
What's the reason for that?

**Comment by jakub300** [comment]
As the solution to above request, if the client want's to make changes he can do that in unminified file and swap url in the base.twig without necessity for our developer to modify build task, build and send new build to the client.

**Comment by luboskmetko** [comment]
@jakub300 why not, that's probably the most versatile. Feel free to implement it, but let me review the PR.
