### ISSUE TITLE
yo:page command doesn't seem to work

### ISSUE THREAD

**Issue by arturkot** [xfiveco/generator-chisel#25]
Example:

![zrzut ekranu 2016-08-04 21 48 15](https://cloud.githubusercontent.com/assets/1224792/17416180/4eb6da5a-5a8d-11e6-97c4-c1b93dd74f17.png)

Setup:
* Node v5.11.0
* NPM 3.8.8
* Yo 1.8.4
* generator-chisel 0.1.2

Is it me or something is wrong?

**Comment by luboskmetko** [comment]
That's strange. Can you run ``yo --help`` to check if the page subgenerator is listed under chisel generator? Can you also run ```yo doctor``` to see if everything's ok in your system?

**Comment by arturkot** [comment]
Hey @luboskmetko ,

Here's what `yo --help` outputs:

```
Available Generators:

  xh
    page
    wp
  chisel
```

`yo doctor`:

```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
```

I've tried again on a different computer and with Node v6.3.1 and, again, I couldn't use `yo chisel:page`.

**Comment by luboskmetko** [comment]
Thanks, @arturkot. Can you please update the generator to the latest release (0.1.4) and try again? 

I've just listed the page sub generator in package.json, didn't realize it was recommended when using `generators` folder for storing generators. It's possible this was the reason why the page generator wasn't available for you. Don't know why, but it worked for me, though. The output should look like this:

```
chisel
  page
```

Let me know if it works now. Thanks!

**Comment by arturkot** [comment]
It works! \o/

Thanks. :)
