### ISSUE TITLE
Improve vendor concatenation

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#254]
This issue lists improvements that should be done to the vendor concatenation.

* [ ] Feed gulp with files not a list of files
Currently we are feeding gulp with list of files from `vendor.json` and let handle gulp reading from fs. That may lead to weird situations when user will specify glob, or specify the same file twice.
* [ ] Watch file listed in `vendor.json` for changes

**Comment by luboskmetko** [comment]
This functionality is not available in the new version
