### ISSUE TITLE
Remove get_ from twigs wherever possible

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#257]
Examples:
```
main_nav.get_items -> main_nav.items
subitem.get_link -> subitem.link
```

**Comment by luboskmetko** [comment]
@jakub300 I can do this so we move on with issues a bit, but can you tell me what's reason for it?

**Comment by jakub300** [comment]
Best practices I guess. [Timber considers many of them deprecated](https://github.com/timber/timber/blob/fc625e1a913ed16023ae1a0f21fe0b25299da32c/docs/upgrade-guides/1.0.md#deprecated). For example `MenuItem`'s `get_children` and `get_link` we are using in the `main-nav.twig` are marked `@internal` [in the timber code](https://github.com/timber/timber/blob/cf29ba26c3de0d2ed507da664336d159fa03ebf3/lib/MenuItem.php#L184).
