### ISSUE TITLE
Default screen after running `gulp`

### ISSUE THREAD

**Issue by arturkot** [xfiveco/generator-chisel#26]
What should I do to take a look at a default page?

After running `gulp` I see:

![zrzut ekranu 2016-08-04 22 01 53](https://cloud.githubusercontent.com/assets/1224792/17416644/672f5916-5a8f-11e6-80ba-4b625d90388c.png)

Meanwhile in our XH generator it looks like this:

![zrzut ekranu 2016-08-04 22 05 02](https://cloud.githubusercontent.com/assets/1224792/17416673/897871ce-5a8f-11e6-9b2f-2c2192c07e69.png)

I'm not sure If I should take some additional action after `yo chisel`?

**Comment by thymikee** [comment]
@arturkot I'm pretty sure this was resolved in #23, waiting to be released. Meanwhile you can pull from `master`

**Comment by arturkot** [comment]
Thanks!

**Comment by luboskmetko** [comment]
It works a little bit differently than in the XH generator. When you first generate project there isn't any project index, it's only created when you add new pages. The project index is created dynamically from the list of pages in `.yo-rc.json` and using `project-index.html` as a template (solution taken from Piotrek's generator).

So you first need to add some pages and then run `gulp`, but I guess we need to first resolve #25 for you.
