### ISSUE TITLE
Change .dev to .test

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#261]
Looks like we should change .dev to .test to avoid problems - https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

@jakub300 @arturkot what you think?

**Comment by jakub300** [comment]
Seems like necessary thing to do. Since this change is fresh maybe we could wait and see how it develops until next Chisel release?

**Comment by luboskmetko** [comment]
Yes, the next release should be fine.

**Comment by marcinkrzeminski** [comment]
I'm going to send a PR soon ;).
