### ISSUE TITLE
Replace normalize with postcss-normalize

### ISSUE THREAD

**Issue by marcinkrzeminski** [xfiveco/generator-chisel#271]
Since we don't support legacy browsers anymore it might be a good idea to replace the standard normalize with https://github.com/jonathantneal/postcss-normalize which can be configurable like the autoprefixer we also use.

**Comment by jakub300** [comment]
Hey, great idea, we will be introducing `browserlist` integration as part of #260 so I will probably do this and #260 together.

**Comment by marcinkrzeminski** [comment]
👍
