### ISSUE TITLE
Set browser caching for static resources

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#278]
CSS, scripts, images, etc.

**Comment by marcinkrzeminski** [comment]
Hi,

@luboskmetko do you mean using .htaccess with mod_expiers and friends? I could do that. Let me know if I should work on that.

**Comment by luboskmetko** [comment]
Hi Marcin,

yes, could be something simple like here https://varvy.com/pagespeed/leverage-browser-caching.html but I would set caching for CSS/JS for 1 year as we have files revisioning. You can also take a look at .htaccess generated by WP Rocket, they have more advanced version with more file types covered.

Reassigning to you, thanks!

**Comment by marcinkrzeminski** [comment]
Hi @luboskmetko ,

finally found the time to work on this. You think we should do this only for WP projects or both types?

**Comment by marcinkrzeminski** [comment]
Hi again,

I just pushed some code for the WP project only. Here's the code: https://github.com/xfiveco/generator-chisel/compare/master...marcinkrzeminski:feature-278?diff=split&expand=1&name=feature-278

I have taken most of it from https://github.com/h5bp/html5-boilerplate/blob/6.0.1/dist/.htaccess. It worked for me in the past pretty well. 

I did some tests on my local and the expiration time is respected as per .htaccess file.

**Comment by luboskmetko** [comment]
@marcinkrzeminski thanks and sorry for the late reply. It looks good to me, can you please create a PR?

**Comment by marcinkrzeminski** [comment]
I just did a PR ;).
