### ISSUE TITLE
Fix wp_title in base.twig

### ISSUE THREAD

**Issue by JakubSzajna** [xfiveco/generator-chisel#284]
I've encountered the problem that in example Yoast SEO plugin overwrites page title via hook, so writing ```{{ wp_title }} - {{ site.name }}``` or just ```{{ site.name }}``` can be problematic, as you cannot predict what settings does user have and if it does not duplicate the site name in example.

And I believe the plugin is even printing site title and site description via wp_head action, so not only the content is duplicated, but the whole <title> occurs two times.

Maybe we should somehow warn developers of that behaviour?

**Comment by luboskmetko** [comment]
Encountered this as well with Yoast SEO. However, it only duplicates titles if the _Force rewrite titles_ is enabled - https://wordpress.org/support/topic/where-is-force-rewrite-titles-2/. Need to check if default Chisel installation with Yoast SEO does that.

If so, we should probably add `add_theme_support( 'title-tag' );` and then just do in `base.twig`

```
{% if wp_title %}
  {{ wp_title }}
{% else %}
  {{ site.name }}
{% endif %}
```

**Comment by luboskmetko** [comment]
Ok, in default installation Yoast SEO only adds `site.name` to the title but doesn't duplicate title element because `Force rewrite titles` is disabled by default

**Comment by jakub300** [comment]
I'm for the `add_theme_support( 'title-tag' );`, but it's my understanding that [it is replacement](https://developer.wordpress.org/reference/functions/add_theme_support/#title-tag) to `wp_title()` and they should not be used together.

**Comment by luboskmetko** [comment]
@jakub300 you're right, if we use it we need to remove the title tag. I'll try to send a PR in conjunction with #281
