### ISSUE TITLE
Disable WP emojis polyfill

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#285]
In default WP installation Emojis JS is loaded, we could disable it either by installing https://wordpress.org/plugins/disable-emojis/ plugin or by copying code from it to a new Chisel class. Thoughts?

**Comment by jakub300** [comment]
Why?

**Comment by luboskmetko** [comment]
It ads additional DNS prefetch and another request but it's just a polyfill for older browsers. Emojis work even without it in modern browsers.

![chisel-emojis](https://user-images.githubusercontent.com/176712/31390815-2e77c1f4-add5-11e7-9caa-6ae2bfbbf3bb.png)

**Comment by marcinkrzeminski** [comment]
👍  on that. Anyone recall if any of our customers did use that? 

I would do it without the plugin if we decide on that. I could actually work on that if we decide to disable it.

**Comment by luboskmetko** [comment]
Thanks, @marcinkrzeminski. I'm wondering if using the plugin wouldn't be better because if we want to do it properly we will have copy the [code from the plugin](https://github.com/ryanhellyer/disable-emojis/blob/master/disable-emojis.php) anyway. Then we will have to maintain that code while with plugin it's up to its author https://wordpress.org/support/plugin/disable-emojis and you can easily update the plugin to fix issues.

Also deactivating plugin if someone needs that WP emojis polyfill is more flexible than updating the theme code.

**Comment by marcinkrzeminski** [comment]
Yeah there are always some up and downsides of each solution ;). I just like to keep the number of plugin as low as possible, my personal preference. The downside of going with plugin is that the customer could always disable the plugin ;). I guess we need to decide what's more important for us. Despite the solution we choose I'll be willing to implement it anyway. If we go for a plugin solution you think we should give the developer an option to install this plugin or not like we have for Gravity and other plugins.

**Comment by JakubSzajna** [comment]
I also prefer keeping number of plugins as low as possible. But if we will have to copy the code from the plugin to the chisel it does not make sense. What if plugin gets updated? You will update the code in chisel? WP will handle that automatically if it will be a plugin.
I'd say we install the plugin and activate it by default. Then developer can disable/remove it when he is sure he does not need it.

**Comment by marcinkrzeminski** [comment]
I'm OK with that ;). What about the others?

**Comment by luboskmetko** [comment]
For me it's ok too :) We can later document which plugins are installed by default (Timber, obviously, and this one) and explain why.

**Comment by marcinkrzeminski** [comment]
👍  When we have a decision you can assign it to me and I'll work on it when heaving some time to spare ;)

**Comment by luboskmetko** [comment]
@marcinkrzeminski thanks, I've invited you to collaborate on the project so I can assign this to you then :)
