### ISSUE TITLE
Not sure what's the reason for using .gitattributes

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#30]
I mean specifically `* text eol=lf`.
This causes troubles with PNG images and popular fonts formats like woff, woff2, otf, ttf on UNIX machines.

I have never had troubles working on the repository without `.gitattributes` specified, regardless the OS of the collaborators.

**Comment by luboskmetko** [comment]
I think this was to prevent auto conversion to CRLF on Windows which is quite annoying and clashes with Editorconfig setting.

But for sure, we can update this to more safer https://github.com/xfiveco/generator-xh/blob/master/app/templates/gitattributes (and add twig extension there)
