### ISSUE TITLE
GSAP error building for production

### ISSUE THREAD

**Issue by mrfrancescomoro** [xfiveco/generator-chisel#302]
Hello, I am new to this generator and maybe I am doing something wrong or I don't get how it works but, I run the "gulp build" command to move my project from local environment to my online hosting.
I get an error that says that 'TimelineMax' is not defined 'Cubic' is not defined.
I don't get it, it works fine locally, why should it be a problem when I try to build it?

I'm lost.
Thanks in advance
Francesco

**Comment by arturkot** [comment]
Hi @mrfrancescomoro ,

any chance you could provide your code so I could take a look, try to reproduce the error? Could even be via email. From what you've described there's _something_ wrong with dependencies. Can't tell what exactly just from the description.

Cheers,

Artur Kot

**Comment by mrfrancescomoro** [comment]
Hi @arturkot 
this is what i do to import the libraries:

import $ from 'jquery';
import { TweenMax } from 'gsap';
var scrollMonitor = require('scrollMonitor');

if you need all the code I'll post it no problem.

Thanks again

**Comment by arturkot** [comment]
@mrfrancescomoro Just sent you private message.

**Comment by arturkot** [comment]
Judging on the code you've provided the issue has been caused by missing imports (you were referring to undefined variables). Update your imports:

```
import $ from 'jquery';
import TimelineMax from 'gsap/src/uncompressed/TimelineMax';
import TweenMax from 'gsap/src/uncompressed/TweenMax';
import { Cubic } from 'gsap/src/uncompressed/easing/EasePack';
```

and let me know if it works for you.

**Comment by arturkot** [comment]
An alternative approach is keeping your original code and adding

```
/*global Cubic, TimelineMax*/
```

at the top of `app.js`. This will let the linter know you expect use global variables.

Whatever works best for you!
