### ISSUE TITLE
Lando - database setup issues

### ISSUE THREAD

**Issue by Kwapi** [xfiveco/generator-chisel#310]
When running `yo chisel` from a directory that has a lando container there are issues with the database setup.

There's two breaking points:
1. The initial check to make sure the database host is reachable after putting in the database host and port values
2. The creation of a new database

The final wp-config for Lando should have their `internal_connection` values but putting them at the 1st step results in a failed connection (probably because it's not run within the docker). Disabling that check could help move things forward. The other option is to put the `external_connection` values which pass the 1st step but then break at the 2nd step when WP-CLI is trying to set-up a new database and it requires the `internal_connection` values.

Have you guys considered Docker setups?

**Comment by jakub300** [comment]
Hey,

I'm not familiar with Lando but my understanding is that you are using Lando only to provide _AMP_ (apache, mysql, php) environment while running chisel itself outside of docker.

We are aware of the complexity of Chisel dependencies and plan to create docker environment for Chisel (#205). Compared to your setup our goal is to run everything inside Docker (including node) making Docker only required software. In your setup you still need node (to create, build projects), php and mysql (for wp-cli) outside of docker.

You may try to configure things to have the same host and port internally and externally, for example, adding host `database` to `/etc/hosts` but I don't think we are going to specifically support such mixed environments in Chisel.

**Comment by kristjankoppel** [comment]
+1 to Kwapi

We use also Lando and bumped on same problem. I get error like:
`/usr/local/lib/node_modules/generator-chisel/helpers/index.js:21
        throw err;
        ^
Error when checking database,,env: mysqlcheck: No such file or directory`

And plugins are not installed and database is not set up. I get that you try to configure Docker on your own but Lando is part of a stack and all the work don't end up only with WP+Docker and Chisel :) 

Have a try: https://docs.devwithlando.io

**Comment by kristjankoppel** [comment]
@luboskmetko I'm using Mac. 

But you are correct. I'll try make lando "recipe" that would include node, npm/yarn, etc...Then it would be possible to do something like "lando yo chisel" and everything should then run inside docker containers and lando.

At the moment i had some problem with lando itself(latest beta release) so i need to start with that :) Keep you posted if any success.
