### ISSUE TITLE
Remove ES6 from the setup options, make it default to every project

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#322]

**Comment by jakub300** [comment]
This was discussed during eslint/prettier implementation, I think @arturkot had some arguments against this, Artur?

**Comment by luboskmetko** [comment]
Here I was just looking for ways to simplify setup, but if there are some issues with it, we can keep it as an option.

**Comment by arturkot** [comment]
@jakub300 I discussed it with @luboskmetko and agreed we should do it. FYI – **personally** I think it's a good update. We'll just make the project less accessible for less experienced devs.
