### ISSUE TITLE
Updating 'Sandbox' theme will delete 'src' folder

### ISSUE THREAD

**Issue by adammarton** [xfiveco/generator-chisel#328]
And breaks the whole env. Is this how it's supposed to work?

**Comment by luboskmetko** [comment]
@adammarton can you please share more details about how you setup Chisel with the Sandbox theme? Thanks

**Comment by adammarton** [comment]
This is getting interesting. Chisel installs WP with the theme named 'Sandbox'. Is this intentional?
My install folder is named 'sandbox' and I've left all options 'as is' during the install of Chisel, therefore my theme is named '[Sandbox](https://wordpress.org/themes/sandbox/)'. WP installs it and immediately cries to update it (which I've did) and my 'src' folder automagically disappears. Could be this an unfortunate namespace collision with 'sandbox'?

**Comment by luboskmetko** [comment]
@adammarton indeed, this is a name collision with the Sandbox theme. Chisel gets a project name from the folder name it's installed in and it creates a start theme with the same name as the project name. 

What you could do except installing Chisel to a folder with different name or not updating Sandbox theme, is to install it in `sandbox` folder but to set a different project name, eg. `My Sandbox`.

However, when setting up WordPress from the command line, use `Sandbox`:

```
? Enter title for the new site: Sandbox
? Enter URL: http://sandbox.test/
```

Chisel then installs the start theme into `my-sandbox`. Finally, you have to add a correct proxy target to `.yo-rc.json`, after `chiselVersion`, add `"proxyTarget": "sandbox.test"`

Let me know if this helps. Thanks

**Comment by adammarton** [comment]
@luboskmetko just using a different project name (other than 'sandbox') solves the issue.

May I ask if this is an issue with Chisel or WP in general? One may choose a different but also problematic name for his project and this could happen again.

**Comment by luboskmetko** [comment]
@adammarton it seems this is a problem in general, they are trying to address https://core.trac.wordpress.org/ticket/14179. So it's safer not to use common words as theme names.

We'll try to solve it in Chisel as well to prevent such collisions. So thanks for pointing this out.

**Comment by adammarton** [comment]
@luboskmetko omg, such an old (and frustrating) issue.

Thank you for the great support!

**Comment by luboskmetko** [comment]
@adammarton np, you're welcome.
