### ISSUE TITLE
Remove page

### ISSUE THREAD

**Issue by illycz** [xfiveco/generator-chisel#343]
How can I properly remove generated page?
I removed file from templates, but I don't know, where I can update pages array: `<% if (locals.pages) { %>`.

Thanks

**Comment by illycz** [comment]
Sorry, I'm forgot mention, that I removed also page from `.yo-rc.json`.
When I start dev server, index page still contain link to nonexistent page.

Thanks

**Comment by illycz** [comment]
"Remove page" functionality would be great!

**Comment by luboskmetko** [comment]
Actually, I've just learned that when running `yo chisel:page` without any argument it will regenerate project index. So it should be easier as you don't have to use that trick with adding new page.
