### ISSUE TITLE
Yeoman generator proxy entry doesn't work

### ISSUE THREAD

**Issue by davidrhoderick** [xfiveco/generator-chisel#352]
I'm just starting to use this and I'm trying to make it work with my current MAMP Pro setup, which uses ports 8888, 8890, and 8889 (I mention this because I feel this may be part of the issue).  When I run the generator and enter http://mydevserver.local:8888 as the site address it completes seemingly alright.  But when I start gulp and check Browsersync, it is proxying http://mydevserver.test, which is what it wanted to use on default but isn't what I entered.

So the generator isn't working correctly, that is probably a bug.  I'm going to look for where to change the proxy address now but if anyone can point me in the right direction before I find it, that would be helpful.

Thanks for making this xfiveco; I was just about to make it myself but you guys beat me there.  Maybe I can hop on and fix things as I have the time but I just wanted to say thanks.

**Comment by davidrhoderick** [comment]
OK I found that in dev-vhost.conf mydevserver.test was listed so I changed it (that was the only location), but it is still proxying that address.  Where would it be getting that address?

**Comment by davidrhoderick** [comment]
I found that in gulp/serve.js after generation, under the serve task, there is a const called browserSyncConfig where target is defined as `generatorConfig.proxyTarget || \`${name}.test\``, so I guess it isn't accepting my http://mydevserver.local:8888 value in the generator config and replacing it with `${name}.test`.

**Comment by jakub300** [comment]
Hi David,

Chisel partially ignoring URL provided during setup is a bug (#189). `proxyTarget` was added as a temporary, manual fix.

`proxyTarget` can be configured in `.yo-rc.json`:
```
{
  "generator-chisel": {
    "config": {
      "name": "...",
      "author": "...",
      ...
      "proxyTarget": "http://some-target/"
    }
  }
}
```

Or if you don't want to commit your `proxyTarget` to repository you can also create file `.yo-rc-local.json` with similar content:
```
{
  "generator-chisel": {
    "config": {
      "proxyTarget": "http://some-target/"
    }
  }
}
```

@luboskmetko We probably should document use of `proxyTarget` until real fix is implemented.

**Comment by luboskmetko** [comment]
Thanks for checking out Chisel @davidrhoderick. Let us know if the above fix works for you. 

@jakub300 documented here https://www.getchisel.co/docs/development/tasks/
