### ISSUE TITLE
Improve font rendering

### ISSUE THREAD

**Issue by piotr-bajer** [xfiveco/generator-chisel#360]
Hi guys, I often get comments from clients that on macos fonts look bolder. Can we add following style rules:
```
* {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility
}
```

It may go at the top of `elements/_html.scss` file (https://github.com/xfiveco/generator-chisel/blob/13602e6389d07bc2e91177ec20c3001ae0b76ab8/generators/app/templates/styles/itcss/elements/_html.scss)

**Comment by jakub300** [comment]
Definitely, but I think it's enough to do it on `html`, no need for `*`.

**Comment by piotr-bajer** [comment]
@jakub300 You are right, both properties are inherited, can be applied to `html`
