### ISSUE TITLE
Generator fails with error on Windows

### ISSUE THREAD

**Issue by trejster** [xfiveco/generator-chisel#361]
For a fresh install of chisel on Windows 10 I get the following error when calling yo chisel in a new directory:

![image](https://user-images.githubusercontent.com/5671026/38468827-488f3e22-3b43-11e8-9c66-1c5fccd0e6fa.png)

**Comment by jakub300** [comment]
Hey, do you have php installed? `php` command must be in terminal to setup WordPress projects.

**Comment by trejster** [comment]
@jakub300 thankyou - yep that was the problem, doh!
