### ISSUE TITLE
Update dependencies of generated projects

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#371]
Running  `npm audit` on a generated project reveals a bunch of vulnerabilities in packages, mostly in packages with major version updates (gulp, gulp-sass, gulp-stylelint)

@jakub300 what you think how severe are those? Also would you find time to work on this?

Thanks

**Comment by jakub300** [comment]
Hey,

Project I'm working on is finishing so there is a chance I will have some time to work on Chisel.

Code in projects is run on developers machines, we don't use those modules with untrusted outside data so in general I don't think those security problems apply to us.

**Comment by luboskmetko** [comment]
Thanks, good to know.

**Comment by jakub300** [comment]
Separated stylelint update to #374
