### ISSUE TITLE
Remove default WordPress themes and plugins

### ISSUE THREAD

**Issue by rafalgic** [xfiveco/generator-chisel#373]
I think that we should get rid of the default WordPress themes - they take space and most of the time aren't even used and (most probably will never be).

Similarly Akismet and Hello Dolly are barely ever used (the latter - probably never). Let's get rid of them, hmm?

**Comment by luboskmetko** [comment]
Sounds like a good idea to me. Moreover they always report _updates available_ in WP admin which is a bit annoying.

**Comment by rafalgic** [comment]
I'm not sure how to do it, so feel free to assign to anyone else.

**Comment by luboskmetko** [comment]
I guess this will be done during installation using WP-CLI.

@jakub300 can you take a look on this when you have time? Thanks
