### ISSUE TITLE
Remove `declaration-block-properties-order` from stylelint

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#38]
Currently it's sorted alphabetically for some unknown reason. 
I believe the `declaration-block-properties-order` property should be removed from config as it's more of an obstacle than help for maintaining stylesheets.

**Comment by luboskmetko** [comment]
I added this because personally I prefer alphabetical order, as it doesn't require much thinking and is easy to order. But for sure we can remove it.

**Comment by thymikee** [comment]
👍
