### ISSUE TITLE
Deployment 

### ISSUE THREAD

**Issue by jaydeesigns** [xfiveco/generator-chisel#386]
Hey guys, I've had a great time learning twig and chisel and the process has been fairly easy, thanks a lot for putting up this framework! However, I've hit an obstacle when uploading my site to my client's hosting place and I haven't found a lot about the db config environments. I suppose things would be much simpler if I could just clone my repo but unfortunately I am dealing with a shared hosting account.

I uploaded my files and excluded the wp-config-local.php file, then included db name, user, password and host in the wp_config.php file. But when I try to load the site I get this:

![error_db](https://user-images.githubusercontent.com/16673480/43410639-328d67e0-93ed-11e8-9bc2-1467390b160d.png)

If I edit **wp-config.php** and replace this:
define( 'DB_NAME', $_SERVER['dbname'] );
define( 'DB_USER', $_SERVER['username'] );
define( 'DB_PASSWORD', $_SERVER['password'] );
define( 'DB_HOST', $_SERVER['localhost'] );

with: 
define( 'DB_NAME', 'dbname' );
define( 'DB_USER', 'username' );
define( 'DB_PASSWORD', 'password');
define( 'DB_HOST', 'localhost');

my site now works but I feel this is not the way I should be handling this. Is there anything I am missing? Thank you for you help!

**Comment by jakub300** [comment]
Hi Jay,

This is not my area of expertise but I don't think that doing it the way you did it is necessarily bad. It is generally a bad practice to keep configuration like that hardcoded in the code, but often it is necessary. Some hosting providers (like [Pantheon](https://pantheon.io/docs/read-environment-config/)) set variables with database access automatically, some others may let you manually set any variables you want but in many cases shared hostings don't have such functionality.

**Comment by luboskmetko** [comment]
Glad to hear you like working with Twig/Chisel, Jay.

What you did to make your site work on shared hosting is pretty much the only option you often have - you need to hardcode host's DB credentials to `wp-config`.  I wouldn't worry about this too much, because there really isn't anything to do about it unless hosting offers some more advanced config management like Jakub mentioned.

**Comment by jaydeesigns** [comment]
Thank you guys for your answers. For now I will have to do it this way then. Do you recommend Pantheon?

**Comment by marcinkrzeminski** [comment]
We recommend Pantheon to our customers as a hosting platform of choice. If you can afford it, you should give it a try. It offers a lot of great features including dev, test, prod environment, SSL, CDN, backups, and much more.
