### ISSUE TITLE
Change button component to object (c-btn -> o-btn)

### ISSUE THREAD

**Issue by piotr-bajer** [xfiveco/generator-chisel#390]
Can we change button component `.c-btn` to `.o-btn` and move it to objects? I am talking about the component from this file: https://github.com/xfiveco/generator-chisel/blob/master/generators/app/templates/styles/itcss/components/_btn.scss

The reasoning behind this is the following. Often button component is included in other components and needs some additional styling, but if component's name makes it being included before button component, the developer is forced to use higher priority declaration in order to override default button style. Some simple example is presented in this pen: https://codepen.io/Piotr-Bajer/pen/NBMLYw

If a button component was an object, it would be always included before any component and developer could easily override it.

also I think `margin: 0; /* [4] */` can be removed from button component as it is default for all elements.

**Comment by luboskmetko** [comment]
@piotr-bajer if you need variations of button component you should add them in `_btn.scss` using modifier like `.c-btn--primary` there.  At least, this is how it's traditionally done if you treat button like a separate component. That would help you avoid the problems you mentioned.

However, I know that depending on UI this can bring additional issues so now that you store styling for a component in two different files. So I see your point with changing the button to object which would have some common characteristics and particular button style would be achieved with additional buttons components or with a button as an element inside other components.

@arturkot @jakub300 what you think?

**Comment by arturkot** [comment]
It depends on a project IMO. Sometimes button can be a component, sometimes it's better when it lands in an object land (I used both approaches). I'm indifferent to button being an object then. :) Will adapt it to the project requirements anyway. :P
