### ISSUE TITLE
How we can use chisel in existing WordPress dev environment like vvv or local-by flywheel 

### ISSUE THREAD

**Issue by dazunE** [xfiveco/generator-chisel#393]

**Comment by luboskmetko** [comment]
This is not supported out of box but it might be possible to achieve by changing configuration a bit, see related issues:

- https://github.com/xfiveco/generator-chisel/issues/387
- https://github.com/xfiveco/generator-chisel/issues/310

Also a developer has created custom Vagrant Box for Chisel https://github.com/robertguss/Vagrant-Chisel
