### ISSUE TITLE
Add Solution to Common Gravity Forms Related issues

### ISSUE THREAD

**Issue by gicolek** [xfiveco/generator-chisel#394]
I found a neat workaround related to the issues with Gravity Forms inline JavaScript 
and our defer tags that causes the forms to bug out in some case scenarios.

https://bjornjohansen.no/load-gravity-forms-js-in-footer (edited)
This solves 90% of the javascript issues related to Gravity Forms.

Please add that to the documentation under WordPress common issues.

**Comment by luboskmetko** [comment]
Added into the new section at the bottom of this page https://www.getchisel.co/docs/development/wordpress/
