### ISSUE TITLE
Add Twig Extensions

### ISSUE THREAD

**Issue by mortensassi** [xfiveco/generator-chisel#399]
How do you add twig extensions? For example i need the `Twig_Extension_Debug()` What i can see is that you can add Filters, Functions and Tests, but no Extensions?

**Comment by jakub300** [comment]
Hey, I guess you can just write `$twig->addExtension(...);` in [`extendTwig`](https://github.com/xfiveco/generator-chisel/blob/818bf39acb8508e29042fbfc04f3734c9ce2442d/generators/wp/templates/chisel-starter-theme/Chisel/Extensions/Twig.php#L22). I'm not sure if helper could help in any way with that.

Regarding `Twig_Extension_Debug` all you have to do is set [`WP_DEBUG` in wp-config-local.php](https://github.com/xfiveco/generator-chisel/blob/818bf39acb8508e29042fbfc04f3734c9ce2442d/generators/wp-config/templates/wp-config-local.php#L47) and [Timber will add it](https://github.com/timber/timber/blob/e9a39d2f59fe2adfefa66e08a0bd1b4d505c553e/lib/Loader.php#L167).

**Comment by mortensassi** [comment]
Thanks it works!
