### ISSUE TITLE
Custom Post Type results in 404 (Not Found)

### ISSUE THREAD

**Issue by mortensassi** [xfiveco/generator-chisel#401]
I followed the tutorial on [xfive.co](https://www.xfive.co/blog/mvc-like-wordpress-development-acf-timber/) but i get an error when i want to display single CPT

**What i did**
* Add Custom Post Type in the `Chisel/Extensions/DataType.php` and register it as `offer`
* Create `single-offer.php`
* Create `templates/single-offer.twig`
* Navigate to `mysite.lo/offer/offer-1`

**What i get**
* Default single page with Message: `Sorry, we couldn't find what you're looking for.`
* Console Error Output: `GET http://localhost:3000/angebot/ausbildung/ 404 (Not Found)`

**Code**
````php
<?php

namespace Chisel\Extensions;

/**
 * Class DataType
 * Use this class to register custom post types and taxonomies
 * @package Chisel\Extensions
 */
class DataType implements ChiselExtension {
	public function extend() {
		add_action( 'init', array( $this, 'registerPostTypes' ) );
		add_action( 'init', array( $this, 'registerTaxonomies' ) );
	}

	/**
	 * Use this method to register custom post types
	 */
	public function registerPostTypes() {
		$offerLabels = array(
          'name'               => __( 'Offers' ),
          'singular_name'      => __( 'Offer' ),
          'menu_name'          => __( 'Offers' ),
          'name_admin_bar'     => __( 'Offer' ),
          'add_new'            => __( 'New Offer', 'offer' ),
          [...]
      );

      $offerArgs = array(
          'labels'                => $offerLabels,
          'description'           => __( 'Beschreibung.'),
          'public'                => true,
          [...]
      );

	register_post_type('offer', $offerArgs);
	}

	/**
	 * Use this method to register custom taxonomies
	 */
	public function registerTaxonomies() {
	}
}

````

**Comment by mortensassi** [comment]
Flushing the re rewrite rule from dashboard `Settings -> Permalinks` by clicking on save did the trick 🤦‍♂️

**Comment by luboskmetko** [comment]
@mortensassi thanks for checking out Chisel! Glad to hear you found what the problem was. I've just added a short note regarding this here https://www.getchisel.co/docs/development/pages/
