### ISSUE TITLE
Replace gulp-uglify with gulp-uglify-es

### ISSUE THREAD

**Issue by mortensassi** [xfiveco/generator-chisel#404]
When writing js-code in ES6 format, the `build` task fails with an `GulpUglifyError:Unable to minify JavaScript`

To fix this, you need to install the [gulp-uglify-es](https://www.npmjs.com/package/gulp-uglify-es) package. I've tested it and it worked!

**Comment by jakub300** [comment]
Hi, while this is correct solution this may be indication of some problem. If you intend to support older browsers like IE 11 there should be no ES6 code in your build and uglify should not fail.

Nonetheless, as part of migration to Babel v7 we added support for browserslist (so you can configure which browsers you would like to support) and migrated to uglify-es so this is already implemented (#397).
