### ISSUE TITLE
Warning: Declaration of Chisel\Image::srcset() should be compatible with Timber\Image::srcset($size = 'full') in userpath/site/wp/wp-content/themes/theme_path/Chisel/Image.php on line 42

### ISSUE THREAD

**Issue by jaydeesigns** [xfiveco/generator-chisel#406]
Hello guys, still learning here! I am getting this error when enabling debug mode.

Warning: Declaration of Chisel\Image::srcset() should be compatible with Timber\Image::srcset($size = 'full') in <user>/<site>/wp/wp-content/themes/<theme_path>/Chisel/Image.php on line 42

How can I address this? Thank you!

**Comment by luboskmetko** [comment]
@jaydeesigns sorry for the late reply, looks like it's fixed here https://github.com/xfiveco/generator-chisel/pull/405. This should be in the next Chisel release this month, so please fix it manually in your project in the meanwhile. Thanks!
