### ISSUE TITLE
Error: Extracting a zip file requires ZipArchive.

### ISSUE THREAD

**Issue by djboris88** [xfiveco/generator-chisel#407]
Hello,

I am having this issue when trying to setup project with command `yo chisel`, both with `sudo` and without it. I am using Linux Mint 19.1 (Cinnamon).

```shell
   ...
   create gulp/tasks/vendor.js
   create dev-vhost.conf
Downloading WordPress 5.0.2 (en_US)...
Error: Extracting a zip file requires ZipArchive.

/usr/local/lib/node_modules/generator-chisel/helpers/index.js:21
        throw err;
        ^
1
```

**Comment by jakub300** [comment]
Hey,

It looks like you don't have zip extension for php installed. It should be possible to install by
```bash
sudo apt-get install php-zip
```
But I cannot be sure if it works for your configuration.

**Comment by djboris88** [comment]
Yes, thank you! I supposed it is an easy fix, but I couldn't google a solution. I am kind of new to linux.

**Comment by djboris88** [comment]
I've hit another issue now.. Plugin archives seems to be corrupted, but I can download them manually and unzip them, they are perfectly fine.

<pre>Downloading installation package from https://github.com/wp-premium/advanced-custom-fields-pro/archive/master.zip...
Unpacking the package...
<font color="#34E2E2"><b>Warning:</b></font> The package could not be installed. &quot;PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure&quot;
Downloading installation package from https://github.com/wp-premium/gravityforms/archive/master.zip...
Unpacking the package...
<font color="#34E2E2"><b>Warning:</b></font> The package could not be installed. &quot;PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure&quot;
Downloading installation package from https://github.com/wp-sync-db/wp-sync-db/archive/master.zip...
Unpacking the package...
<font color="#34E2E2"><b>Warning:</b></font> The package could not be installed. &quot;PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure&quot;
Downloading installation package from https://github.com/wp-sync-db/wp-sync-db-media-files/archive/master.zip...
Unpacking the package...
<font color="#34E2E2"><b>Warning:</b></font> The package could not be installed. &quot;PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure&quot;
<font color="#EF2929"><b>Error:</b></font> No plugins installed.

/usr/local/lib/node_modules/generator-chisel/helpers/index.js:21
        throw err;
        ^
1
</pre>

**Comment by jakub300** [comment]
I don't know what can be a problem. We had situations when the GitHub was serving bad archives but that usually goes away on second attempt. At this moment only think I can suggest is not selecting them during project creation and installing them manually later.
