### ISSUE TITLE
Add note about Twig coding standards

### ISSUE THREAD

**Issue by JakubSzajna** [xfiveco/generator-chisel#408]
Hey,

I think there should be a link in the docs to the Twig Coding Standards as I can see some people do not follow them.
https://twig.symfony.com/doc/2.x/coding_standards.html

I was looking for some JS Twig linter, but apparently, there isn't any or I could not find one :(
There is a composer linter that requires PHP 7.1, has some other dependencies and is written for PHP's composer, so not sure if we want to go this way.

**Comment by marcinkrzeminski** [comment]
Since PHP 5.x is dead I guess the PHP version is not an issue I guess. The composer factor might be a blocker here, however, if we decide to include composer in our stack we could start including other linters like phpcs and maybe ditch the bundled wp-cli and install plugins via composer.

**Comment by JakubSzajna** [comment]
We've been there with a composer and if I remember well it wasn't so good. But I do not remember why ;) And correct me if I'm wrong, but the support for plugins in repositories is really bad or there isn't any.

And I doubt people would pay for PHPStorm if they do not use it already as there are really good free alternatives for it.

**Comment by marcinkrzeminski** [comment]
As of the plugins we have this: https://github.com/wp-premium, not sure if it covers all the plugins we use. 

What are good free alternatives for PHP Storm? I've tried Sublime and VS Code and there is always something that is missing and makes me come back to PHP Storm ;/.

**Comment by luboskmetko** [comment]
I'll add link to Twig standards to the documentation. 

Regarding Twig linter, not sure if it's worth to add a new dependency just for that. Also in Chisel linting CSS/JS files works together with Prettier - so you don't have to care about formatting. Prettier for PHP is just alpha and there probably won't be any for Twig anytime soon.

As for composer there were various issues with it, for example https://github.com/xfiveco/generator-chisel/issues/111

**Comment by luboskmetko** [comment]
Added note here https://www.getchisel.co/docs/development/twig/. I'm closing this but we can get back to this idea once there are better tools available.
