### ISSUE TITLE
Prevent caching dev versions of static files

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#409]
Because of the expire settings in [.htaccess](https://github.com/xfiveco/generator-chisel/blob/master/generators/wp/templates/.htaccess) dev version of static files like `main.css`, `app.bundle.js` are cached for long time. This can result in cached files being used by browser instead of the updated files which can be quite confusing.

@jakub300 @JakubSzajna any ideas how to solve this while keeping expires settings for the build version?

**Comment by luboskmetko** [comment]
Per @marcinkrzeminski suggestion the following update to `revisionPath` function should solve this:

```
...
return sprintf(
  '%s/%s%s%s',
  get_template_directory_uri(),
  \Chisel\Settings::DIST_PATH,
  trim( $asset, '/' ),
  '?' . time()
);
...
```

If that's ok, I would submit PR.

**Comment by jakub300** [comment]
Is it working OK with browsersync css reloading? Also query string in
production may somehow impact cdn caching.

Wt., 8.01.2019, 12:38: Lubos Kmetko <notifications@github.com> napisał(a):

**Comment by luboskmetko** [comment]
@jakub300 seems to work ok with browsersync. Also it would be only used in dev mode so only [here](https://github.com/xfiveco/generator-chisel/blob/master/generators/wp/templates/chisel-starter-theme/Chisel/Extensions/ChiselTwig.php#L129). Revisioning of production files would work like now.
