### ISSUE TITLE
ESLint Brace Style Configuration

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#41]
[Current configuration](https://github.com/xfiveco/generator-chisel/blob/292bfcfacf8aa6d89ba929760776f3a2c0315007/generators/app/templates/.eslintrc.yml#L17) ([docs](http://eslint.org/docs/rules/brace-style)) requires braces to be written like that:

```javascript
if (foo) {
  bar();
} else {
  baz();
}
```

While [your coding standards](https://github.com/xfiveco/js-coding-standards/blob/9ab5acdb0f3faf70fbbc3c1e916ae5a23e0f6305/README.md#control-structuresl) require them to be written like that:

```javascript
if (foo) {
  bar();
}
else {
  baz();
}
```

One or the other should be updated. Change in generator would be breaking for existing projects.

**Comment by thymikee** [comment]
@jakub300 I'd rather update our coding standards. 
cc @luboskmetko

**Comment by luboskmetko** [comment]
I've updated the coding standards.
