### ISSUE TITLE
Add an alternative versions of jQuery

### ISSUE THREAD

**Issue by marcinkrzeminski** [xfiveco/generator-chisel#442]
How about adding jQuery Slim?
https://code.luasoftware.com/tutorials/webpack/force-jquery-slim-import-in-webpack/
or https://sizzlejs.com/ as extra options?

With some info like use Slim if you don't need Ajax, etc, or Sizzle if you want just a selector engine.

**Comment by luboskmetko** [comment]
The new version won't support jQuery
