### ISSUE TITLE
[question] keep project updated

### ISSUE THREAD

**Issue by mortensassi** [xfiveco/generator-chisel#451]
I'm not sure if i can just update all the dependencies in package.json in order to tackle all the vulnerabilities that get output from `yarn audit` – Is it safe to upgrade to the latest versions? i guess not? Is there a good workflow in how to keep my project in sync with your latest changes?

**Comment by luboskmetko** [comment]
@mortensassi do you mean vulnerabilities in a generated project or in the Chisel generator itself? In the generated project there only seems to be 6 vulnerabilities with high severity, all coming from Gulp. We use the latest 3.* version (3.9.1), unfortunately we haven't had time to upgrade to 4.* yet (upgrading Gulp to v4 would most likely not work out of box)

Regarding Chisel itself, we plan to look at dependencies and update those. 

In general, there isn't a straightforward workflow to use new versions of Chisel on already generated projects. Chisel does most of its job when scaffolding the project and there isn't an option to regenerate the project with new Chisel version while keeping existing work. What you could do is to generate a new project separately and copy changes you want to the existing project.

Let me know if you have any other questions.
