### ISSUE TITLE
Prevent "regeneratorRuntime is not defined" 

### ISSUE THREAD

**Issue by mortensassi** [xfiveco/generator-chisel#452]
I came around an issue while using async functions, like in [this post](https://github.com/babel/babel/issues/8829#issuecomment-481210475) and the last comment helped me solving this problem in my chisel project – Maybe it's something you consider implementing.

**Comment by luboskmetko** [comment]
@mortensassi thanks for pointing that out.

@jakub300 maybe you could take a look when you have time?
