### ISSUE TITLE
Update generator dependencies

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#453]

**Comment by piotr-bajer** [comment]
It would be nice to update WP-CLI, currently, on PHP 7.4 it produces the following notice during `yo chisel` command:
`Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in phar://lenovo/AppData/Roaming/nvm/v10.9.0/node_modules/generator-chisel/helpers/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP
_CLI/DocParser.php on line 75
`

**Comment by luboskmetko** [comment]
@piotr-bajer @marcinkrzeminski hey guys, I've just published a [new version](https://github.com/xfiveco/generator-chisel/releases/tag/v0.16.1)  - can you check if updating generator with `npm i -g generator-chisel` updates WP-CLI as well? Thanks

**Comment by piotrkulpinski** [comment]
@luboskmetko I've just generated WP project with PHP 7.4.4 and it went smoothly.

**Comment by luboskmetko** [comment]
Thanks, @piotrkulpinski!
