### ISSUE TITLE
Code simplified header

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#469]
**Simplified header**

It the first phase we will build a simplified header:

* [x] logo
* [x] main navigation
* [x] GitHub icon pointing to https://github.com/xfiveco/generator-chisel

![image](https://user-images.githubusercontent.com/176712/96132706-021d8000-0efb-11eb-9af2-2ad087b585ce.png)

**Full header**

Refer to 

![image](https://user-images.githubusercontent.com/176712/96132978-18c3d700-0efb-11eb-98dc-2a4bf628f2d8.png)

**Comment by luboskmetko** [comment]
@edenizk this looks like done except that link color in the main navigation isn't violet but black now.

**Comment by edenizk** [comment]
> @edenizk this looks like done except that link color in the main navigation isn't violet but black now.

Changed to violet(primary color)

**Comment by luboskmetko** [comment]
Cool, thanks. I'm wondering if the hover effect could be changing to the orange.

Also the Chisel in logo is underlined currently.

**Comment by luboskmetko** [comment]
@edenizk can you make active link orange? So on About page, the About would be orange. Thanks

**Comment by edenizk** [comment]
@luboskmetko, I've changed the active link color to orange

**Comment by luboskmetko** [comment]
Thanks
