### ISSUE TITLE
Review and update documentation for the new version

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#470]

**Comment by edenizk** [comment]
Hi @luboskmetko , 

**[wildcard virtual hosts setup for Linux](https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/installation/wildcard-virtual-hosts#linux)**
 which you've mentioned, I can remove that, but then the users will not have the Linux setup.
You can view previous content on the [Wayback Machine](https://web.archive.org/web/20200219082058/http://brunodbo.be/blog/2013/04/26/setting-up-wildcard-apache-virtual-host-wildcard-dns). The closest example I could find to the Linux tutorial is what we have for the [Mac setup](https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/installation/wildcard-virtual-hosts#macos). If you'd want I can try that setup in my Linux and create content based on differences 

**[Wp sync DB](https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/setup/wordpress#4-setting-up-an-existing-project)**, 
I see that it's redirecting to xfive wikis,
but what I think is that ppl outside of xfive might get a little bit confused
I've found this tutorial which we can exchange with https://wptips.dev/wp-sync-db/

**For the post.data in**:
https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/development/static-content#post-object
 
it didn't have a description, I have added one, but wonder if it was just a general title for the below content? or had a missing content only.
Let me know so I can remove it

**Comment by luboskmetko** [comment]
@edenizk 

- good find with the Wayback machine, please link to it
- that page `Setting up WordPress projects at Getfives` we will have to move from GitHub to new Xfive wiki. For now, please link to the article you found
- not sure about that post object, but if we refer to this https://rewrite-with-webpack-docs--getchisel.netlify.app/docs/development/static-content and it seems it has that description there

**Comment by edenizk** [comment]
@luboskmetko,

I've made the first 2 changes, actually, I see that it's also missing in the link you've shared.

![image](https://user-images.githubusercontent.com/35309972/120220607-50d71a80-c23d-11eb-92a4-742e63e0c1bd.png)

**Comment by luboskmetko** [comment]
@edenizk thanks, got it. Indeed, it looks like there was missing content there. So if that's what it stores, it looks fine to me :)

**Comment by edenizk** [comment]
@luboskmetko, Ok so I will be keeping the content I've added :)
