### ISSUE TITLE
Code Why Chisel section on homepage

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#472]
* [x]  title
* [x]  static svg illustrations
* [x]  reasons with title and texts
* [x] CTA at the bottom (give Chisel a star)

![image](https://user-images.githubusercontent.com/176712/96141797-a9051a80-0f01-11eb-9649-d19aa1e7e5b5.png)

**Comment by luboskmetko** [comment]
@edenizk can you please check illustrations when changing resolution? Seems they are loosing their aspect ratio and get distorted.

**Comment by edenizk** [comment]
@luboskmetko,

- [x] fixed the ratio problem

**Comment by luboskmetko** [comment]
Thanks, looks good.
