### ISSUE TITLE
Code documentation page

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#475]
* [x] sidebar navigation pointing to documentation subpages
* [x] main content
* [x] On this page - on page navigation scrolling to subsections of the page

For the reference how this should work see https://nuxtjs.org/guides/get-started/installation

![image](https://user-images.githubusercontent.com/176712/96144071-0ef2a180-0f04-11eb-9bc0-c5c6cde33860.png)

**Comment by luboskmetko** [comment]
@edenizk On this page links are coded as designed but now it looks like some margin between items wouldn't be bad. Here it's 0.75em https://www.screencast.com/t/3uaaNQ5LJk2

**Comment by luboskmetko** [comment]
hi @edenizk I have a few remarks to on this page navigation yet:

- when going from page with On this page navigation to a page without it, the main content jumps from middle to right like here https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/setup. Could we make it so the main content is centered even on the page without On page navigation?
- I would make the font-size of the on page navigation items smaller to make it look more "local" and add a bit of size contrast to the documentation navigation on the left. Here it is reduced to 16px on desktop resolution https://www.screencast.com/t/ZR9jodYt
- then we have page like this https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/simple where on page navigation doesn't look good and probably doesn't make sense to have it there too. Would it be possible o turn it off for some pages if we wanted?

Thanks

**Comment by edenizk** [comment]
- [x] Content centered even if it's without on-page navigation
- [x] On-page navigation font size reduced to 16px
- [x] Attribute added for disable on page sidebar

**Comment by luboskmetko** [comment]
@edenizk this looks ok, please close.
