### ISSUE TITLE
Implement code highlighting

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#476]
For the code highlighting we could use https://highlightjs.org/static/demo/ and Shades of purple style

I've never worked with highlight.js but it is popular, actively developed and with low number of issues. If there's any problem with it we could use https://prismjs.com/ as an alternative (that's what we use on the current website).

**Comment by edenizk** [comment]
Hi @luboskmetko, I see that Prism js implemented the project https://github.com/xfiveco/generator-chisel/blob/rewrite-with-webpack-docs-redesign/docs/src/scripts/app.js#L9  
Is this task still valid?

**Comment by luboskmetko** [comment]
@edenizk actually, yes. Can you try to use highlightjs with Shades of purple theme like mentioned above? I think that Prism implementation was just a temporary update to the existing code, but that code highlighting currently doesn't look that good (a few font colors are too dark)

**Comment by edenizk** [comment]
@luboskmetko, I understood, thank you for your answer. I will exchange with the Highlightjs

**Comment by luboskmetko** [comment]
@edenizk this looks fine, you can close the issue.
