### ISSUE TITLE
Code previous / next navigation 

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#478]
This is used on documentation pages:

![image](https://user-images.githubusercontent.com/176712/96144457-7ad50a00-0f04-11eb-877b-afab08808233.png)

**Comment by luboskmetko** [comment]
@edenizk could we make Previous and Next text part of clickable area? Ideally this would be clickable area https://www.screencast.com/t/fCafbX1Ld. Thanks

**Comment by edenizk** [comment]
- [x] Clickable area increased like in the image

**Comment by luboskmetko** [comment]
@edenizk seems ok, please close.
