### ISSUE TITLE
Add basic content styling 

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#479]
Basic content styles like titles, paragraphs, links, lists etc.

![image](https://user-images.githubusercontent.com/176712/96144595-a1934080-0f04-11eb-83ce-69174f7c8adb.png)

**Comment by edenizk** [comment]
@luboskmetko, yes I also wanted to talk with you about that. We can exchange links with blue + underline. But if we will add an inline code just blue color then it can conflict with the bold text. What about if we will mark them as GitHub does? So for the inline code, it would look like in the image:
![image](https://user-images.githubusercontent.com/35309972/118000837-72cc3400-b346-11eb-9fd6-0952c7a90a6b.png)
Of course maybe with a different color.

Ok, I will make the titles closer to the content, thank you for your feedback 🙂

**Comment by luboskmetko** [comment]
@edenizk actually, I like that idea to do it similarly to GitHub. I've tried it here https://www.screencast.com/t/yXoRC0QJo and I think it's more readable in case of such heavy usage of inline code.

I've used background color from design, because there was such instance of inline code too (#F0F1F3), but also reduced the font-size to 0.889em, plus added some small padding.

**Comment by luboskmetko** [comment]
@edenizk styles for unordered lists are either missing or not displayed yet - should be small orange square like in the design. Thanks

**Comment by edenizk** [comment]
- [x] orange square added back

**Comment by luboskmetko** [comment]
@edenizk I think we have everything here, you can close this.
