### ISSUE TITLE
Style content tip

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#480]
A short tip with icon used in the content

![image](https://user-images.githubusercontent.com/176712/96144711-c25b9600-0f04-11eb-95d2-8be4166bfe0b.png)

**Comment by luboskmetko** [comment]
@edenizk can you please show this in action? That tip displayed above is on https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/setup/static (the last paragraph before section 3.) Thanks

**Comment by edenizk** [comment]
@luboskmetko, I've added the tip styling to the place you mentioned.
Earlier I've also added here for a demo: https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/docs/setup/wordpress
But let me know if it was a mistake. I can remove the tip styling from it.

**Comment by luboskmetko** [comment]
@edenizk thanks, it can stay there, I didn't notice it before :)
