### ISSUE TITLE
Add "empty" scrollbar when there's less content

### ISSUE THREAD

**Issue by marcinkrzeminski** [xfiveco/generator-chisel#490]
Hey,

please add the `overflow-y: scroll` property to the HTML element, so we can avoid horizontal content jumping.

Video here: https://cln.sh/loLBME

**Comment by edenizk** [comment]
Hi @marcinkrzeminski, 

Thank you for letting me know about it 🙂.

I have added `overflow-y: auto` to the HTML element. adding `scroll` is causing short pages to look a bit strange 
e.g. https://rewrite-with-webpack-docs-redesign--getchisel.netlify.app/about

What is the browser you are using? I couldn't recreate the problem. 
If you could verify that issue has been fixed on your end, I would be glad.

**Comment by marcinkrzeminski** [comment]
@edenizk to me it looks strange when the page is jumping ;), but maybe that's my personal preference. I'm on macOS using Brave browser, but it looks the same on Chrome or Firefox as well.

**Comment by edenizk** [comment]
Hi @marcinkrzeminski,

I am using brave too, but in Windows 😁

Thank you for letting me know. I didn't notice sth on my BrowserStack tests, but I will try once more with both Chrome and Firefox 🙂
