### ISSUE TITLE
Add custom 404 page

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#494]
@edenizk can you please add a custom 404 page? Can be as simple as https://www.screencast.com/t/ra1juvrYtA3. Talk to @jakub300 if some configuration on Netlify is required. Thanks

**Comment by edenizk** [comment]
@luboskmetko, I have added the 404 page you can view on https://www.getchisel.co/there-is-no-page-like-this 🙂

**Comment by luboskmetko** [comment]
Cool, thanks!
