### ISSUE TITLE
Too many arguments issue on setup without yarn

### ISSUE THREAD

**Issue by edenizk** [xfiveco/generator-chisel#495]
I found the problem causing too many arguments, if you will look at my setup without yarn(image 1) and with yarn(image 2) you will see that npx is somehow diving process.argv into nodes whenever there is a space. I was reading that we can either wrap inside another quote(e.g '"SELECT 1"' ), or wrapping between `SELECT 1`, or with replace 'SELECT 1'.replace(/ /g, '\\ ') (not sure if it will work in Macs tho) and this should solve the problem :slightly_smiling_face: . 
![image (5)](https://user-images.githubusercontent.com/35309972/121032982-15dc6600-c7ac-11eb-8198-5ecaff9a621c.png)
![image (6)](https://user-images.githubusercontent.com/35309972/121032991-17a62980-c7ac-11eb-8dc0-c8a7b2116ea5.png)

But even tho this will solve the problem with the DB setup there will be a problem if the user has space in the folder name like "Test 3" and it will also create another too many arguments problem :sweat_smile:. You can also find the description in the [execa docs](https://github.com/sindresorhus/execa#execacommandcommand-options)

I have the problem with testing that because some of these commands are inside chisel-plugin-wordpress or chisel-scripts, and they are running from node_modules inside the project(which is pulled from npm package page), I couldn't find a way to test them locally. I have tried to test with the jest, but jest doesn't detect too many arguments problem.

**Comment by luboskmetko** [comment]
@edenizk thanks for researching this.

@jakub300 can you advise on this? Seems to be pretty common issue (recently one of our candidates got into that too). Thanks

**Comment by jakub300** [comment]
This issue is caused by bugs in npm (v6 if I remember correctly) on Windows. Issue is not happening after updating npm or using yarn.
