### ISSUE TITLE
Setup travis-ci.com

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#502]
Hi @luboskmetko,

It looks like travis-ci.org has been deprecated and it's not running tests anymore and migration to https://travis-ci.com/ is necessary.

After logging to travis-ci.com go to https://travis-ci.com/account/migrate, enable beta migration, setup Github App with access to generator-chisel repo (not sure if enabling beta or app setup is first) and migrate generator-chisel repository.

**Comment by luboskmetko** [comment]
@jakub300 should be done. Let me know if anything else is needed
