### ISSUE TITLE
Auto loading most frequently used wp plugins

### ISSUE THREAD

**Issue by JakubSzajna** [xfiveco/generator-chisel#53]
The generator should have the list of most frequently used wp plugins and ask to add them to composer.json file while generating the project.

Examples: ACF, Gravity Forms

**Comment by rafalgic** [comment]
I propose adding:

https://wordpress.org/plugins/wp-migrate-db/

This plugin: https://github.com/wp-sync-db/wp-sync-db is outdated and should be removed.

My personal development favourites are also:


What the File
Duplicate Post
Better Search Replace

**Comment by thymikee** [comment]
Pawel suggested `Backup Buddy`

**Comment by piotrusin** [comment]
Definitly ACF as mentioned by Kuba.
And also:
WooCommerce
Regenerate Thumbnails
Adminer
User Switching

**Comment by luboskmetko** [comment]
A few more suggestions:

- Disable Emojis - for performance reasons
- Stream
- iThemes Security
- Optimize Database after Deleting Revisions
- Post Types Order
- WP Google Authenticator - for 2 factor authentication
- WP Updates Notifier
- Yoast SEO or The SEO Framework (https://wordpress.org/plugins/autodescription/)

**Comment by thymikee** [comment]
So lets go with **ACF** and **Backup Buddy** for starters. We'll add more later.

**Comment by jakub300** [comment]
Backup Buddy download source?

**Comment by thymikee** [comment]
Fixed with #81
