### ISSUE TITLE
Reorganize templates

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#58]
Currently all templates are stored (or rather buried) in `generators/app/templates`. This makes them less obvious and only accessible for the main generator.

Using [template context](http://yeoman.io/authoring/file-system.html) we could move all templates to the root folder so they are easier to maintain and other sub generators can use them as well. 

Something like this works, though probably it could be refactored to a universal utility

```
'use strict';

var yeoman = require('yeoman-generator');

var test = yeoman.Base.extend({
  paths: function () {
    this.sourceRoot(this.sourceRoot() + '/../../../templates');
  },

  writing: function () {
    this.fs.copyTpl(
      this.templatePath('twig/index.twig'),
      this.destinationPath('templates/index.twig'),
      { title: 'Templating with Yeoman!' }
    );
  }
});

module.exports = test;
```

This way we could for example use the same Twig templates when generating front-end and WP projects with front-end.

**Comment by luboskmetko** [comment]
In the above examples the index.twig is stored in the root folder in `templates\twig\index.twig` (while in the current setup it would be in `generators\app\templates\templates\twig\index.twig`

**Comment by luboskmetko** [comment]
As discussed we should also move [chisel starter theme](https://github.com/xfiveco/chisel-starter-theme) to the generator and use it as an another template for scaffolding project. Currently the theme is installed with Composer as a dependency but that dependency is then erased so developer can edit theme (so it's not a dependency anyway). Moving the theme to the generator would help us to:

- use Yeoman templating engine for easy template updates, eg. project name in various theme files
- easy add or remove certain code or files based on the user input (eg. remove assetPath function for WP only projects)
- use and maintain same Twig templates for front-end and WP projects (eg. base.twig)
- having all WP related files in one place

**Comment by JakubSzajna** [comment]
Not sure why you want to remove assetPath function from wp only projects as it can still be useful, the only change would be to not use manifest file during path generation as it will not be used there.
Also as we were saying during our conversation, lets put it on hold at least until there won't be any major changes in the theme files.

**Comment by luboskmetko** [comment]
That was just an example of theme customization based on the project type. But maybe someone wants just enqueue styles on WP only projects.

Anyway, this has milestone 0.4 so it's not planned for the next release.

**Comment by jakub300** [comment]
Is this still being discussed or is it ready to be implemented?

**Comment by luboskmetko** [comment]
You can work on it. Maybe I would put twig, itcss and browserify directly to the templates folder not like it is now (styles/itcss, etc.)

**Comment by jakub300** [comment]
TODO:
* [ ] After moving `chisel-starter-theme` verify whether `.gitignore` is renamed by npm installation

**Comment by jakub300** [comment]
@luboskmetko I'm not really sure what beyond moving `chisel-starter-theme` into generator should I do here?

Should I move templates into root directory as described in first two comments? I don't really understand reasons for that. Such move seems to create mess because we would not know which files belong to which generator. Also generated file tree would be very different from the one inside generator and that creates further possibility for bugs and problems.

**Comment by luboskmetko** [comment]
@jakub300 I thought it would be a kind of abstraction looking at templates as independent building blocks used by various (sub)generators. For example, Twig templates are used both in front-end project and WP projects but there are currently 2 different sets of them, compare:

- https://github.com/xfiveco/generator-chisel/blob/master/generators/app/templates/templates/twig/_base.twig
- https://github.com/xfiveco/chisel-starter-theme/blob/master/templates/layouts/base.twig and header for example https://github.com/xfiveco/chisel-starter-theme/blob/master/templates/partials/html-header.twig

So at minimum we need to sync and maintain these manually so developers work with approx. the same set of templates in the both types of projects (of course, WP projects will have some additional templates). Ideally we would just maintain one set of templates but I don't know if it's possible to do in a reasonable way. If moving templates to the root would just complicate things, we don't have to do that.

Alternatively, I was thinking about breaking the main generator to smaller subgenerators and using `composeWith` function. In such case we could keep relevant templates in the subgenerator folder - eg. itcss subgenerator would contain all ITCSS stylesheets while another CSS methodology generator would contain its structure. Then based on user preference you could `composeWith` with one or another from the main generator.

Anyway, I'm ready to close this issue if you don't see any benefit of such refactoring at this point.

**Comment by thymikee** [comment]
@luboskmetko what I think about this issue is that we shouldn't over-engineer the solutions that don't cause problems or bugs yet. 

In my opinion we should close this issue and get back to it when we start seeing problems with maintaining these templates.

After moving the `chisel-starter-theme` to our generator though, we can think of extracting common templates into, let's say `/templates/shared` directory located in the root, if it's not too complicated :)

**Comment by luboskmetko** [comment]
Sure, no problem. I've added #97 to fix differences in Twig templates.
