### ISSUE TITLE
Generating WordPress project type

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#6]
Generating WP project will involve things like:

- install WordPress & Timber
- create theme folder from name-slug 
- copy template files to the theme folder
- copy Timber base theme files
- remove Gulp templates task (as Twig templates are supported by Timber)
- add custom assetPath function to Twig to load default or revisioned styles/scripts, decide when to load which one (proxy test?) 
- do not create project index when running page subgenerator
- allow custom wp-config and other setup
- adjust coding style to codex (tabs?)

**Comment by luboskmetko** [comment]
Composer would be probably the best option to manage WP, Timber and plugins as dependencies. A couple of resources:

- https://selfteach.me/install-wordpress-plugins-composer/
- https://davidwinter.me/install-and-manage-wordpress-with-composer/
- https://deliciousbrains.com/storing-wordpress-in-git/
- https://roots.io/using-composer-with-wordpress/
- https://roots.io/wordpress-plugins-with-composer/
- https://roots.io/bedrock/

**Comment by thymikee** [comment]
@luboskmetko our back-end dev Kuba have setup Timber with WP recently for Chisel-generated project. I'll ping him so he can provide some information on the changes he made, so we could set that up faster.

**Comment by thymikee** [comment]
@jakub300 I'd like to assign you to this task (although GitHub doesn't allow me to do it 😢). @luboskmetko and Kuba from our office will guide you through the concepts and an implementation plan.
