### ISSUE TITLE
Create Chisel website and documentation

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#60]
A simple page presenting Chisel, based on the index page design

**Comment by thymikee** [comment]
Removing the milestone, as it's a presentation layer of Chisel, not tied to the generator itself. Looking forward for this page though! 👍

**Comment by jakub300** [comment]
Tools used by various sites:
* https://facebook.github.io/react/ -> http://jekyllrb.com/
* http://redux.js.org/ -> https://www.gitbook.com/
* https://vuejs.org/ -> https://hexo.io/
* https://onsen.io/ -> http://www.metalsmith.io/

**Comment by luboskmetko** [comment]
Thanks, adding some more:

- https://timber.github.io/docs/ - http://gohugo.io/
- https://www.gatsbyjs.org/ - this one looks pretty interesting, would be nice if we can build the site as PWA to test things and learn something new
