### ISSUE TITLE
Functionality plugin

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#61]
Generating a functionality plugin to store site specific functionality like custom post types, taxonomies, etc.

**Comment by JakubSzajna** [comment]
This is definitely a good idea to move custom data from theme to custom plugin.
Another cool functionality would be to prefix plugin class with project slug name to avoid redefinition of the class that could exist somewhere in the code. This redefinition attempt produces error in PHP.

**Comment by luboskmetko** [comment]
@JakubSzajna @jakub300 guys, what you think of this setup of the functionality plugin https://github.com/luboskmetko/generator-chisel/tree/issue61/generators/wp/templates/functionality-plugin. For now there is just one example of Analytics class, but I'd like to add those others for Performance, Security, etc. 

My question is if we need to create a plugin with custom namespace (with project name) or the Site namespace is ok here (or maybe MySite)? With Site it would be easier as we wouldn't have to rename folder and classes during the project generation. But I would at least store the plugin in folder with project slug name.

**Comment by JakubSzajna** [comment]
I'd use project slug name for both directory (plugin name) and for namespace if it's not a big problem.

Also maybe you can create a separate class for defining shortcodes that can be used inside of templates to allow the real separation of the plugin's bussiness logic and theme's views.

Also I am thinking about making a separate "modules" for different parts of custom logic that we need to implement during site creation. Something like seperate namespaces proposed here, maybe MySite\Features\Module1, MySite\Features\Module2.

Another part could be ACF definitions, but this could be made as a parts of specific modules.

**Comment by jakub300** [comment]
I like the idea but we should be careful what we use it for, analytics for example doesn't se like something what would require that kind of solution. Also, like always it would be nice to have option during setup to disable plugin creation.

**Comment by luboskmetko** [comment]
Following our discussion and the work on #206 I'm closing this one.  

Some reasoning behind this decision:  

We will now focus on promoting good development practices by separating functionality into logical, easy to extend pieces in the theme itself. 

While functionality plugin is considered a good practice in reality it's often difficult to decide whether certain functionality should belong to the plugin or the theme. Even if it wasn't, functionality plugin adds another layer of complexity and developer needs to switch between two places during development (plugin and theme).

Finally, in theory functionality plugin should allow easy theme switching while keeping site related functionality intact. However, I guess it's rarely such straightforward process because changing the theme usually means changing the site functionality too.
