### ISSUE TITLE
Provide a way to move front-end src to WP theme folder

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#64]
This is a followup on a discussion we had. 

We agreed that, since we're staying with our current folder structure (`src` at project root, regardless front-end or WP project type), it would be nice to have a guide explaining briefly how developers can move all front-end source files to WP theme folder, so one could edit all src files in one place.

**Comment by luboskmetko** [comment]
@thymikee @jakub300 @JakubSzajna I'm thinking about one alternative yet - would it be possible to move just `src` folder to the theme folder leaving `gulp` and `node_modules` folders in the root folder like they are in the current setup?

Wondering if such setup could solve all our "problems" - developer would have all theme related files in the theme folder, but neither gulp nor node_modules would be there so they shouldn't accidentally copy them. Also developer could still run gulp tasks or git commands just from the root folder. Maybe then we don't have to provide this alternative setup documentation.

**Comment by thymikee** [comment]
Good catch @luboskmetko! That's definitely an option to consider. Although, since it's as easy as copying src to theme folder and adjust chisel config in `package.json` (and this is a good example of using our config), wouldn't it be better to document it instead?

**Comment by luboskmetko** [comment]
I think the less variations or exceptions we have, the better, so I would rather agree on compromise like this.  I see the benefits of the current setup, the only thing which I still find inconvenient is having `src` outside the theme folder. Is there any particular reason to keep it in the root and not placing it inside the theme?

**Comment by danekszy** [comment]
Silly question...
Have you thought about taking a step back and moving WP theme files (including `*.php`) to `src/` and then keeping it in sync with `.../wp-content/...` on changes?
This way development still takes place in `src/` and the `*.php`s are right there to develop custom functionalities and push data to templates.
Depending on the project type (WP vs FE) we could either include or drop the data injection stuff that I proposed recently...
Would that solve our developers' problems?

**Comment by luboskmetko** [comment]
Don't know if that's not too overcomplicated, why to process files we don't have to :)

**Comment by JakubSzajna** [comment]
I don't think we should move whole theme files to the src dir. Backend dev works on the whole wp, he could create not only themes but also plugins and other modifications... Lets just stick to the front-end files and as I said during the call, I don't like to see many external files in the theme dir, but compromise with only src directory there would work for me as long as you remember that all theme files are publicly accessible via direct url. Not sure if it makes a difference for you.

**Comment by luboskmetko** [comment]
I don't think publicly accessible source files are problem, as dist files are generated from them anyway.

Actually, @thymikee @jakub300 would CSS source maps work on a live site with the current structure as the sources won't be uploaded to the site? This could make debugging live site problematic.

**Comment by jakub300** [comment]
I think sources are included in sourcemap but we should verify that.

**Comment by thymikee** [comment]
@luboskmetko since #91 is merged, we can make a brief note about moving front-end source in our README, somewhere in WordPress section. Would like to tackle it?

**Comment by luboskmetko** [comment]
Thanks, I will test it and add a note about it (with 0.4 release note)
