### ISSUE TITLE
Add proper watch for php/twig files in WP projects

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#65]
Replacing `*.php` with `**/*.{php,twig}` [here](https://github.com/xfiveco/generator-chisel/blob/a428b03f98704a23903c414b424c79b2b19a86b8/generators/app/templates/gulp/tasks/serve.js#L27) and limiting that line to WP projects should be enough.

**Comment by thymikee** [comment]
Or we can build on top of #56

**Comment by jakub300** [comment]
Actually I don't see how, we neither build templates nor watch anything in `src/templates`.

**Comment by thymikee** [comment]
Pardon me, you're right. Forgot we're not dealing with template task for WP
stuff

10 paź 2016 23:22 "jakub300" <notifications@github.com> napisał(a):
