### ISSUE TITLE
Console output when no data file

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#71]
Is this how it's supposed to work when there is no data file?

```
[14:27:52] Starting 'scripts-build'...
[14:27:52] Finished 'assets-watch' after 263 ms
{ Error: ENOENT: no such file or directory, open 'C:\xampp\htdocs\www\dev\fives-concept\src\data\projects.twig.json'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\xampp\\htdocs\\www\\dev\\fives-concept\\src\\data\\projects.twig.json' }
[14:27:52] Finished 'templates-watch' after 409 ms
[14:27:52] Finished 'styles-watch' after 846 ms
```

**Comment by danekszy** [comment]
No it's not... Let me check that. Perhaps it's something that was merged in a wrong way (the PRs were merged in different order).

**Comment by danekszy** [comment]
Hey @luboskmetko, 
could you provide me with mode details about this?
Is this still happening on master?
What's your node version?
What's your Win version?

Looks like this shouldn't happen, since the file reading is wrapped in try...catch block...

Thanks,
Daniel.

**Comment by jakub300** [comment]
[Code](https://github.com/xfiveco/generator-chisel/blob/885950f031246cd7eee898c8c5eb4b2fcd213cb0/generators/app/templates/gulp/tasks/templates.js#L17) is written to log when `error.code === 'ENOENT'`, so it worked like in code. I suppose it should be `!==`?

**Comment by danekszy** [comment]
Right, we wanna err on broken JSON, not missing files.
Surprisingly that same code works well for me in the project, even though not every template has its respective data file.
Thanks @jakub300!

**Comment by danekszy** [comment]
Went ahead and pushed this 1-liner directly onto `master`. This shouldn't cause any merge problems, I hope. 😄
