### ISSUE TITLE
Add support for progressively loading CSS

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#72]
Wondering how we could allow this at some point https://jakearchibald.com/2016/link-in-body/

**Comment by thymikee** [comment]
1. We need H/2 on server.
2. This can be partially achieved with critical.css #67

**Comment by luboskmetko** [comment]
Yep, I meant to solve it in conjunction with #67.

**Comment by luboskmetko** [comment]
@arturkot @jakub300 thinking about closing this one as `wontfix` as well. Not sure what's the status of this in Chrome but seems it wouldn't be easy to implement in Chisel.
