### ISSUE TITLE
Custom composer repository for simple installation/update of WP plugins

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#75]
As part of automatized WordPress plugin installation we need to handle cases where we install plugins that are not on [WordPress Plugin Repository](https://wordpress.org/plugins/). We want to download plugins like Gravity Forms and ACF from [wp-premium](https://github.com/wp-premium/) GitHub repositories. Those repositories does not contain `composer.json`  so we need to tell composer what they are different way.

One way of doing that is including definitions in our `composer.json` like [I did](https://github.com/jakub300/generator-chisel/blob/396d7a2f8c240a6d38e82982bec363bdbfc6cb6d/generators/wp/templates/composer.json) in current work-in-progress implementation. It gets trickier when we want to update plugins with `composer update`, composer needs to know that there is new version, that's why i added `pre-update-cmd` hook in `composer.json` linked above. Before each run of update it's increasing all versions defined in packages.

Because it's quite ugly hack, I'd like to suggest other solution. We could create our own composer repository. Composer repository is [simple JSON file](https://gist.github.com/jakub300/e417ecc9d31096d8f1baea06e4a45458/3c05aee8243799f70f368c57481dee5f7b2f01ca) that contains informations about packages and where they can be downloaded from. Unfortunately for `composer update` to work it also has to "change" for composer to know that there is update available. It's done by adding id of the newest commit in `reference` field. We could do that by creating github user and repository that would contain `packages.json` and a travis task we could regularly run by some cron that would regenerate `packages.json` with newest commit ids. 

@luboskmetko, @JakubSzajna, @thymikee let me know what do you think.

**Comment by thymikee** [comment]
I think this is a good idea. It will definitely take a day or two to implement, but I think it's worth it in a long run. 
@luboskmetko any ideas or objections?

**Comment by luboskmetko** [comment]
Sounds good.

**Comment by jakub300** [comment]
Hey Lubos,
I have working version of the repository generator, [it's here](https://github.com/jakub300/custom-composer-repository) right now. There are two branches. One has the code, second the repository file. The travis task that generates repository also needs write access to the repository so I recommend creating separate github user for security reasons.
Please create repository and the user.

**Comment by jakub300** [comment]
[Bot successfully generated](https://github.com/xfiveco/composer-repository/commits/repository) [packages.json](https://github.com/xfiveco/composer-repository/blob/e4068d86f00fc8a34ecd870dcff1358b1edb41fe/packages.json) file 🍾 .

Now we need to run in on regular basis, fortunately [it doesn't seems to be hard thing](https://docs.travis-ci.com/user/triggering-builds).

**Comment by luboskmetko** [comment]
@jakub300 I don't have access to our servers to set this up so reassigning to @ajgon

**Comment by jakub300** [comment]
Igor is on holiday until May 2017

**Comment by luboskmetko** [comment]
@jakub300 good to know :) So assigning to Arek.

**Comment by jakub300** [comment]
Omg, for the second time this week I confused Arek with Artur, of course it should be Arek.

**Comment by arekf** [comment]
Hi guys, I'm afraid I won't be able to get into this in the near future. Milosz suggested to contact our system admins, so they can help you with that.

**Comment by nirnx** [comment]
Hello guys, lets us know (sysadmin) what you need and we do this ;) we prefer contact on slack :)

**Comment by luboskmetko** [comment]
Closing this one as it's not needed anymore.
