### ISSUE TITLE
Use different plugin for sass glob

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#79]
Today when working on a project I wanted to use imports more advanced than `components/*`, for example something like `components/_order-@(started|in_progress|cancelled)`. Unfortunately `gulp-css-globbing` which we currently use requires name to contain `/*` to be recognized as glob. In the project I used `gulp-sass-glob` that requires only `*` to be present at the end so I could write `components/_order-@(started|in_progress|cancelled)*` for example. It's not perfect because `*` still need to be present but it's much better that `/*` requirement.

If there is no opposition I'll prepare pull request.

**Comment by luboskmetko** [comment]
Please do as `gulp-css-globbing` is also not actively maintained anymore.
