### ISSUE TITLE
Add tests for gulp tasks

### ISSUE THREAD

**Issue by jakub300** [xfiveco/generator-chisel#89]

**Comment by luboskmetko** [comment]
@jakub300 what's the status of this? Are you planning to work on this anytime soon or can we close the issue?

**Comment by jakub300** [comment]
I don't think I will have enough time to work on this anytime soon. I'll close PR (#140) but I think we should keep this issue open because the fact that I don't have time to work on this doesn't make it disappear.

**Comment by luboskmetko** [comment]
Makes sense, thanks
