### ISSUE TITLE
Sync front-end project Twig templates and WP starter theme Twig templates

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#97]
Even if we should keep them in sync manually, we should use the same templates code (where applicable) and files structure. Currently there is a lot of differences:

- https://github.com/xfiveco/generator-chisel/tree/master/generators/app/templates/templates/twig/
- https://github.com/xfiveco/chisel-starter-theme/tree/master/templates/

We could do this once we move the starter theme to the generator.

**Comment by thymikee** [comment]
Crucial #99 for this issue has just got merged.

**Comment by luboskmetko** [comment]
This should be done, further improvements can be done in future releases if we add some default components or create components library.
